"""Builds languages/pages/*.json for the Gulf Industrial child theme.

Content source: Gulf_Industrial_Website_Corrected_TrackedChanges_1.docx (tracked changes accepted).
Run: python3 wordpress/tools/build_pages.py
"""
import json
import os

OUT = os.path.join(os.path.dirname(__file__), '..', 'gulf-industrial-child', 'languages', 'pages')


def bullets(text):
    return [t.strip() for t in text.split('•') if t.strip()]


def pipes(text):
    return [t.strip() for t in text.split('|') if t.strip()]


def sec(en, ar, **common):
    return dict(common, en=en, ar=ar)


CTA = sec(
    {'title': "Let's Build the Right Solution for Your Operation.",
     'body': ['Have an industrial challenge, upcoming project, or technical requirement?',
              'Get in touch with Gulf Industrial Solutions and discuss how we can support your operation.']},
    {'title': 'لنبنِ معًا الحل الأنسب لعملياتكم.',
     'body': ['هل لديكم تحدٍ صناعي، أو مشروع قادم، أو متطلب فني؟',
              'تواصلوا مع الخليج للحلول الصناعية لمناقشة احتياجاتكم ومعرفة كيف يمكننا دعم عملياتكم.']},
    type='cta')

PAGES = {}

# ---------------------------------------------------------------- Engineering
PAGES['engineering'] = {
    'slug': 'engineering-services', 'hero_image': 'engineering-hero',
    'en': {'nav': 'Engineering Services', 'eyebrow': 'Engineering Services', 'title': 'Engineering Services',
           'line': 'Expert Field Engineering for Seamless Industrial Operations'},
    'ar': {'nav': 'الخدمات الهندسية', 'eyebrow': 'الخدمات الهندسية', 'title': 'الخدمات الهندسية',
           'line': 'هندسة ميدانية متخصصة لضمان سلاسة العمليات الصناعية'},
    'sections': [
        sec({'eyebrow': 'Engineering Overview', 'title': 'Technical Support for Industrial Operations',
             'body': ['Our engineering services are designed to support the technical and operational requirements of production industries.',
                      'From individual equipment requirements to complete project execution, we provide practical field engineering support across different stages of industrial operations.']},
            {'eyebrow': 'نظرة عامة على الخدمات الهندسية', 'title': 'دعم فني للعمليات الصناعية',
             'body': ['تم تصميم خدماتنا الهندسية لتلبية المتطلبات الفنية والتشغيلية للقطاعات الإنتاجية.',
                      'بدءًا من متطلبات المعدات الفردية وصولًا إلى تنفيذ المشاريع الكاملة، نقدّم دعمًا هندسيًا ميدانيًا عمليًا عبر مختلف مراحل العمليات الصناعية.']},
            type='text', image='engineering-overview'),
        sec({'eyebrow': 'Core Engineering Capabilities', 'title': 'Our engineering capabilities include:',
             'list': ['Process & Operational Parameter Optimisation', 'Industrial Troubleshooting', 'Design & Mechanical Job Services',
                      'Electrical Equipment Installation & Commissioning', 'Process Instrumentation', 'DCS & PLC Support',
                      'Instrument Calibration', 'Turnkey Projects', 'Individual Equipment Installation & Commissioning']},
            {'eyebrow': 'القدرات الهندسية الأساسية', 'title': 'تشمل قدراتنا الهندسية ما يلي:',
             'list': ['تحسين العمليات ومعايير التشغيل', 'استكشاف الأعطال الصناعية وإصلاحها', 'خدمات التصميم والأعمال الميكانيكية',
                      'تركيب وتشغيل المعدات الكهربائية', 'أجهزة القياس والتحكم في العمليات', 'دعم أنظمة DCS وPLC',
                      'معايرة أجهزة القياس', 'المشاريع بنظام تسليم المفتاح', 'تركيب وتشغيل المعدات الفردية']},
            type='list', tone='soft'),
        sec({'eyebrow': 'Process Optimisation & Troubleshooting', 'title': 'Supporting Efficient Industrial Operations',
             'body': ['We provide process and operational parameter optimisation and troubleshooting services to help address technical and operational challenges within production environments.',
                      'Our field engineering teams work across industrial environments to support plant efficiency, operational continuity, and equipment performance.']},
            {'eyebrow': 'تحسين العمليات واستكشاف الأعطال وإصلاحها', 'title': 'دعم كفاءة العمليات الصناعية',
             'body': ['نقدّم خدمات تحسين العمليات ومعايير التشغيل، إضافةً إلى خدمات استكشاف الأعطال وإصلاحها، للمساعدة في معالجة التحديات الفنية والتشغيلية داخل بيئات الإنتاج.',
                      'تعمل فرقنا الهندسية الميدانية في مختلف البيئات الصناعية لدعم كفاءة المصانع، واستمرارية التشغيل، وأداء المعدات.']},
            type='text', image='engineering-process'),
        sec({'eyebrow': 'Mechanical, Electrical & Commissioning', 'title': 'Supporting Equipment Installation and Project Execution',
             'body': ['Our engineering services include design and mechanical job services, along with electrical equipment installation and commissioning.',
                      'We support individual equipment needs as well as broader project scopes, depending on the technical and operational demands of the facility.']},
            {'eyebrow': 'الخدمات الميكانيكية والكهربائية وخدمات التشغيل والتكليف', 'title': 'دعم تركيب المعدات وتنفيذ المشاريع',
             'body': ['تشمل خدماتنا الهندسية خدمات التصميم والأعمال الميكانيكية، إلى جانب تركيب وتكليف وتشغيل المعدات الكهربائية.',
                      'نلبي احتياجات المعدات الفردية، بالإضافة إلى نطاقات المشاريع الأوسع، وفقًا للمتطلبات الفنية والتشغيلية الخاصة بالمنشأة.']},
            type='text', image='engineering-mechanical', flip=True),
        sec({'eyebrow': 'Instrumentation, DCS & PLC', 'title': 'Supporting Process Monitoring and Control',
             'body': ['We provide technical services for process instrumentation, DCS and PLC systems, and instrument calibration, supporting reliable monitoring and control across industrial operations.']},
            {'eyebrow': 'أجهزة القياس والتحكم في العمليات، وأنظمة DCS وPLC', 'title': 'دعم مراقبة العمليات والتحكم بها',
             'body': ['نقدّم خدمات فنية لأجهزة القياس والتحكم في العمليات، وأنظمة DCS وPLC، ومعايرة أجهزة القياس، بما يدعم المراقبة والتحكم الموثوقين في مختلف العمليات الصناعية.']},
            type='text', image='engineering-dcs'),
        sec({'eyebrow': 'Industries We Support', 'title': 'Industry-Focused Engineering Services',
             'body': ['We provide complete engineering services for:'],
             'tags': pipes('Pulp & Paper | Tissue Manufacturing | Converting | Corrugated Packaging'),
             'lead': ['Our support extends from idea to execution, including:'],
             'list': ['Product development', 'Plant efficiency improvement', 'Process troubleshooting',
                      'Technical engineering requirements', 'Equipment installation and commissioning']},
            {'eyebrow': 'الصناعات التي ندعمها', 'title': 'خدمات هندسية متخصصة حسب القطاع الصناعي',
             'body': ['نقدّم خدمات هندسية متكاملة في القطاعات التالية:'],
             'tags': pipes('لب الورق والورق | تصنيع المناديل الورقية | التحويل | التغليف بالكرتون المموج'),
             'lead': ['يمتد دعمنا من مرحلة الفكرة إلى مرحلة التنفيذ، ويشمل:'],
             'list': bullets('• تطوير المنتجات• تحسين كفاءة المصنع• استكشاف أعطال العمليات وإصلاحها• المتطلبات الهندسية الفنية• تركيب وتشغيل المعدات')},
            type='list', tone='soft'),
        sec({'eyebrow': 'Turnkey Projects', 'title': 'From Individual Equipment to Complete Project Execution',
             'body': ['Gulf Industrial Solutions supports turnkey projects as well as individual equipment installation and commissioning.',
                      'Our engineering support can be structured according to the project scope, from specific equipment needs to full-scale execution.'],
             'note': 'From Idea to Execution'},
            {'eyebrow': 'المشاريع بنظام تسليم المفتاح', 'title': 'من تركيب المعدات الفردية إلى تنفيذ المشاريع الكاملة',
             'body': ['تدعم الخليج للحلول الصناعية المشاريع بنظام تسليم المفتاح، إضافةً إلى تركيب وتكليف وتشغيل المعدات الفردية.',
                      'يمكن تنظيم دعمنا الهندسي وفقًا لنطاق المشروع، بدءًا من احتياجات معدات محددة وصولًا إلى التنفيذ الكامل للمشروع.'],
             'note': 'من الفكرة إلى التنفيذ'},
            type='text', image='engineering-turnkey', flip=True),
        sec({'eyebrow': 'Why Choose Gulf Industrial Solutions', 'title': 'Engineering support you can rely on',
             'cards': [['Skilled Field Personnel', 'Onsite engineering expertise for production and industrial facilities.'],
                       ['Practical Engineering Support', 'Solutions focused on real operational and technical needs.'],
                       ['Integrated Capabilities', 'Process, mechanical, electrical, instrumentation, DCS and PLC support.'],
                       ['Project Flexibility', 'Coverage for individual equipment needs as well as turnkey projects.'],
                       ['Industry-Focused Experience', 'Engineering services for pulp & paper, tissue manufacturing, converting, and corrugated packaging.']]},
            {'eyebrow': 'لماذا تختارون الخليج للحلول الصناعية', 'title': 'دعم هندسي يمكنكم الاعتماد عليه',
             'cards': [['طاقم ميداني ماهر', 'خبرة هندسية ميدانية لدعم منشآت الإنتاج والصناعة'],
                       ['دعم هندسي عملي', 'حلول تركّز على الاحتياجات التشغيلية والفنية الفعلية'],
                       ['قدرات متكاملة', 'دعم في مجالات العمليات، والأعمال الميكانيكية، والكهربائية، وأجهزة القياس، وأنظمة DCS وPLC'],
                       ['مرونة في تنفيذ المشاريع', 'تغطية لاحتياجات المعدات الفردية، إضافة إلى المشاريع المتكاملة (تسليم مفتاح)'],
                       ['خبرة متخصصة حسب القطاع', 'خدمات هندسية لقطاعات لب الورق والورق، وتصنيع المناديل الورقية، والتحويل، والتغليف']]},
            type='cards'),
        sec({'eyebrow': 'Saudi Vision 2030', 'title': "Supporting Saudi Arabia's Industrial Growth",
             'body': ["Through skilled field personnel, effective equipment management, and quality-focused engineering support, Gulf Industrial Solutions supports the technical and operational requirements of Saudi Arabia's production industries.",
                      'Our engineering services contribute to industrial development and align with the growing requirements of the Saudi industrial sector and Saudi Vision 2030.']},
            {'eyebrow': 'رؤية السعودية 2030', 'title': 'دعم النمو الصناعي في المملكة العربية السعودية',
             'body': ['من خلال طاقم ميداني ماهر، وإدارة فعّالة للمعدات، ودعم هندسي يركّز على الجودة، تدعم الخليج للحلول الصناعية المتطلبات الفنية والتشغيلية للقطاعات الإنتاجية في المملكة العربية السعودية.',
                      'تسهم خدماتنا الهندسية في التنمية الصناعية، وتتوافق مع المتطلبات المتنامية للقطاع الصناعي السعودي ورؤية السعودية 2030.']},
            type='text', tone='dark'),
        CTA,
    ]}

# ---------------------------------------------------------------- Pulp & paper
def pp(en_eb, en_t, en_body, ar_eb, ar_t, ar_body, image=None, en_tags=None, ar_tags=None, en_list=None, ar_list=None,
       en_after=None, ar_after=None, **kw):
    en = {'eyebrow': en_eb, 'title': en_t, 'body': en_body}
    ar = {'eyebrow': ar_eb, 'title': ar_t, 'body': ar_body}
    if en_tags: en['tags'], ar['tags'] = pipes(en_tags), pipes(ar_tags)
    if en_list: en['list'], ar['list'] = en_list, ar_list
    if en_after: en['after'], ar['after'] = en_after, ar_after
    return sec(en, ar, type='text', image=image, **kw)


PAGES['pulp-paper'] = {
    'slug': 'pulp-paper', 'hero_image': 'pulp-hero',
    'en': {'nav': 'Pulp & Paper', 'eyebrow': 'Pulp & Paper', 'title': 'Complete Solutions for the Pulp & Paper Industry',
           'line': 'From Idea to Execution'},
    'ar': {'nav': 'اللب والورق', 'eyebrow': 'لب الورق والورق', 'title': 'حلول متكاملة لصناعة اللب والورق',
           'line': 'من الفكرة إلى التنفيذ'},
    'sections': [
        pp('Pulp & Paper Overview', 'Supporting Modern Paper Production',
           ['Gulf Industrial Solutions provides solutions for different stages of pulp and paper production, tailored to the specific requirements of each project and production environment.',
            'Our capabilities cover project planning, stock preparation, paper and board machinery, paper machine upgrades, finishing, chemicals, quality control, product development, process optimisation, recycling, wastewater treatment, and technical training.'],
           'نظرة عامة على قطاع اللب والورق', 'دعم إنتاج الورق الحديث',
           ['تقدّم الخليج للحلول الصناعية حلولًا لمختلف مراحل إنتاج اللب والورق، مصممة خصيصًا لتلبية المتطلبات الخاصة بكل مشروع وبيئة إنتاجية.',
            'تشمل قدراتنا تخطيط المشاريع، وتجهيز اللب، ومعدات ماكينات الورق والكرتون، وتحديث ماكينات الورق، وأعمال التشطيب، والمواد الكيميائية، ومراقبة الجودة، وتطوير المنتجات، وتحسين العمليات، وإعادة التدوير، ومعالجة مياه الصرف، والتدريب الفني.'],
           image='pulp-overview'),
        sec({'eyebrow': 'Our Capabilities', 'title': 'Solutions Across the Paper Production Process',
             'list': ['Project Consultation, Planning & Execution', 'Stock Preparation & Recycling', 'Paper & Board Machine Equipment',
                      'Paper Machine Upgrades', 'Finishing & Cutting Equipment', 'Functional & Specialty Chemicals', 'Wood Pulp Supply',
                      'Laboratory Testing & Quality Control', 'New Paper Product Development', 'Process & Operation Optimisation',
                      'Wastewater Treatment', 'Technical Training', 'Turnkey Projects']},
            {'eyebrow': 'قدراتنا', 'title': 'حلول عبر مراحل إنتاج الورق',
             'list': bullets('• الاستشارات والتخطيط والتنفيذ للمشاريع• تجهيز اللب وإعادة التدوير• معدات ماكينات الورق والكرتون• تحديث ماكينات الورق• معدات التشطيب والقص• المواد الكيميائية الوظيفية والمتخصصة• توريد لب الخشب• الاختبارات المخبرية ومراقبة الجودة• تطوير منتجات ورقية جديدة• تحسين العمليات والتشغيل• معالجة مياه الصرف• التدريب الفني• المشاريع بنظام تسليم المفتاح')},
            type='list', tone='soft'),
        pp('Project Consultation, Planning & Execution', 'From Concept to Project Delivery',
           ['We provide consultation, planning, and execution support for pulp and paper initiatives.',
            'Our services can cover early-stage ideas, raw material sourcing, plant layouts, workflow planning, technology selection, and full execution, based on the specific objectives and operational needs of each initiative.'],
           'الاستشارات والتخطيط والتنفيذ للمشاريع', 'من الفكرة إلى تنفيذ المشروع',
           ['نقدّم خدمات الاستشارات والتخطيط والتنفيذ لمبادرات ومشاريع صناعة اللب والورق.',
            'تشمل خدماتنا الأفكار والمراحل الأولية للمشروع، وتوفير المواد الخام، وتخطيط المصانع، وتخطيط سير العمل، واختيار التقنيات المناسبة، والتنفيذ الكامل، بما يتوافق مع الأهداف المحددة والمتطلبات التشغيلية لكل مشروع.'],
           image='pulp-consultation', flip=True),
        pp('Stock Preparation & Recycling', 'Preparing Fiber for Consistent Production',
           ['Our stock preparation solutions support the processing of both virgin and recycled fibers.', 'Equipment includes:'],
           'تجهيز اللب وإعادة التدوير', 'تجهيز الألياف لضمان إنتاج متسق',
           ['تدعم حلولنا لتجهيز اللب معالجة كل من الألياف البكر والألياف المعاد تدويرها.', 'تشمل المعدات:'],
           image='pulp-stock-prep',
           en_tags='Pulpers | Refiners | Cleaners | Screens | Agitators',
           ar_tags='أجهزة تفكيك اللب | أجهزة التكرير | أجهزة التنقية | الغرابيل | الخلاطات',
           en_after=['These systems support fiber preparation, contaminant removal, fiber consistency, energy management, and production throughput.',
                     'Our recycling solutions also support wastepaper collection, sorting, contamination removal, and the recovery of wastepaper for recycling or use as raw material.'],
           ar_after=['تدعم هذه الأنظمة تجهيز الألياف، وإزالة الشوائب والملوثات، والحفاظ على اتساق الألياف، وإدارة استهلاك الطاقة، وتحسين تدفق الإنتاج.',
                     'كما تدعم حلولنا لإعادة التدوير عمليات جمع وفرز الورق المستعمل، وإزالة الشوائب والملوثات، واستعادة الورق المستعمل لإعادة تدويره أو استخدامه كمواد خام.']),
        pp('Paper & Board Machine Equipment', 'Equipment for Paper and Board Production',
           ['We supply equipment for different stages of paper and board manufacturing, including:'],
           'معدات ماكينات الورق والكرتون', 'معدات لإنتاج الورق والكرتون',
           ['نوفّر معدات لمختلف مراحل تصنيع الورق والكرتون، بما في ذلك:'],
           image='pulp-machine', flip=True,
           en_tags='Headboxes | Forming Sections | Press Sections | Dryers | Coaters | Calenders | Rewinding Systems',
           ar_tags='صناديق التوزيع | أقسام التشكيل | أقسام الضغط | المجففات | آلات الطلاء | آلات التقويم | أنظمة إعادة اللف',
           en_after=['Solutions can be selected according to production capacity, paper grade, and project requirements, with support for integration and performance tuning.'],
           ar_after=['يمكن اختيار الحلول وفقًا للطاقة الإنتاجية، ونوع الورق، ومتطلبات المشروع، مع توفير الدعم للتكامل وضبط الأداء.']),
        pp('Paper Machine Upgrades', 'Improving Existing Machine Performance',
           ['We provide paper machine upgrade solutions to support performance improvement, cost reduction, product quality, and production efficiency.', 'Upgrade requirements may include:'],
           'تحديث آلات الورق', 'تحسين أداء الآلات القائمة',
           ['نقدّم حلولًا لتحديث آلات الورق بهدف دعم تحسين الأداء، وخفض التكاليف، وتحسين جودة المنتجات، ورفع كفاءة الإنتاج.', 'قد تشمل متطلبات التحديث:'],
           image='pulp-upgrades',
           en_list=['Mechanical retrofits', 'Automation improvements', 'Energy-efficiency enhancements', 'Performance assessment',
                    'Identification of production gaps', 'Integration of upgraded systems'],
           ar_list=bullets('• التعديلات الميكانيكية• تحسينات الأتمتة• تحسينات كفاءة استهلاك الطاقة• تقييم الأداء• تحديد فجوات الإنتاج• دمج الأنظمة المطوّرة'),
           en_after=['Our approach is based on the existing machine configuration and the specific objectives of the upgrade project.'],
           ar_after=['يعتمد نهجنا على تكوين الآلة الحالية والأهداف المحددة لمشروع التحديث.']),
        pp('Finishing & Cutting Equipment', 'Precision Equipment for Paper Finishing',
           ['We provide equipment for paper finishing, trimming, rewinding, and cutting applications.', 'Solutions include:'],
           'معدات التشطيب والقص', 'معدات دقيقة لتشطيب الورق',
           ['نوفر معدات لتطبيقات تشطيب الورق، والتشذيب، وإعادة اللف، والقص.', 'تشمل الحلول:'],
           image='pulp-finishing', flip=True,
           en_tags='Sheeters | Slitters | Rewinders | Cutters',
           ar_tags='آلات التقطيع إلى شرائح | آلات الشق الطولي | آلات إعادة اللف | آلات القص',
           en_after=['Equipment selection is based on production requirements, setup, and capacity, with a focus on reliable finishing and efficient operation.'],
           ar_after=['يتم اختيار المعدات وفقًا لمتطلبات الإنتاج، وتجهيزات التشغيل، والطاقة الإنتاجية، مع التركيز على تشطيب موثوق وتشغيل فعال.']),
        pp('Functional & Specialty Chemicals', 'Chemical Solutions for Paper & Pulp Applications',
           ['Our functional and specialty chemical solutions support different paper and pulp production requirements.', 'These include:'],
           'المواد الكيميائية الوظيفية والمتخصصة', 'حلول كيميائية لتطبيقات صناعة اللب والورق',
           ['تدعم حلولنا من المواد الكيميائية الوظيفية والمتخصصة مختلف متطلبات إنتاج اللب والورق.', 'وتشمل:'],
           image='pulp-chemicals',
           en_tags='Sizing Agents | Retention Aids | Defoamers | Wet Strength Resins | Dyes | Pigments | Coating Chemicals',
           ar_tags='عوامل تحجيم الورق | مساعدات الاحتفاظ | مزيلات الرغوة | راتنجات مقاومة البلل | الأصباغ | الخضاب | المواد الكيميائية المستخدمة في الطلاء',
           en_after=['Solutions are selected according to specific process and product requirements, with technical assistance, laboratory testing, and process audit support available.'],
           ar_after=['يتم اختيار الحلول وفقًا لمتطلبات العملية والمنتج المحددة، مع توفر الدعم الفني، والاختبارات المعملية، ودعم تدقيق العمليات.']),
        pp('Wood Pulp Supply', 'Pulp Supply for Different Paper Grades',
           ['We provide wood pulp supply solutions covering:'],
           'توريد لب الخشب', 'توريد اللب لمختلف أنواع الورق', ['نقدّم حلولًا لتوريد لب الخشب تشمل:'],
           image='pulp-wood', flip=True,
           en_tags='Softwood Pulp | Hardwood Pulp | Specialty Pulp',
           ar_tags='لب الخشب اللين | لب الخشب الصلب | أنواع اللب المتخصصة',
           en_after=['Our team supports pulp grade selection according to product specifications and production requirements, with sourcing from sustainable and certified forests as part of our current offering.'],
           ar_after=['يدعم فريقنا اختيار نوع اللب وفقًا لمواصفات المنتج ومتطلبات الإنتاج، مع التوريد من غابات مستدامة ومعتمدة كجزء من عروضنا الحالية.']),
        pp('Quality Control & Laboratory Solutions', 'Supporting Consistent Product Quality',
           ['We supply laboratory testing and quality control instruments for pulp and paper applications.', 'Testing solutions cover key parameters including:'],
           'حلول مراقبة الجودة والمختبرات', 'دعم جودة المنتج بشكل متسق',
           ['نوفر أجهزة ومعدات للاختبارات المعملية ومراقبة الجودة لتطبيقات صناعة اللب والورق.', 'تشمل حلول الاختبار قياس المعايير الرئيسية، بما في ذلك:'],
           image='pulp-lab',
           en_tags='Strength | Moisture | Grammage | Surface Properties | Brightness',
           ar_tags='المتانة | الرطوبة | الوزن الأساسي | خصائص السطح | درجة السطوع',
           en_after=['Support includes equipment selection, installation, training, and maintenance.'],
           ar_after=['تشمل خدمات الدعم اختيار المعدات، والتركيب، والتدريب، والصيانة.']),
        sec({'eyebrow': 'More capabilities', 'title': 'Development, efficiency and recovery',
             'cards': [['Developing New Paper & Board Products', 'Our product development support covers new fibers, additives, manufacturing techniques, and the development of specialty papers, custom grades, and packaging-related paper products. Support can extend from concept development to pilot production, depending on project requirements.'],
                       ['Process Optimisation & Plant Efficiency', 'We support manufacturers with process and operational optimisation focused on identifying bottlenecks, energy inefficiencies, process gaps, production waste and equipment underperformance. Solutions may include automation, real-time monitoring, workflow improvements, and process optimisation.'],
                       ['Wastepaper & Recycling Solutions', 'Collection, sorting, contamination removal, and processing to recover wastepaper as a usable raw material, supporting more efficient material utilisation and stronger recycling practices across the sector.'],
                       ['Wastewater Treatment', 'Biological treatment, chemical dosing, filtration and sludge handling, tailored to each facility\'s wastewater characteristics, with support for installation, commissioning, and performance monitoring.'],
                       ['Technical Training', 'Customised training programmes delivered by local and international experts, covering machine operation, process control, quality assurance, maintenance and safety, through workshops and hands-on sessions.'],
                       ['After-Sales, Spare Parts & Technical Support', 'For equipment and systems we supply, support can extend beyond installation: technical assistance, equipment maintenance, performance support, and spare-part requirements, where applicable to the project scope.']]},
            {'eyebrow': 'قدرات إضافية', 'title': 'التطوير والكفاءة واستعادة الموارد',
             'cards': [['تطوير منتجات جديدة من الورق والكرتون', 'يشمل دعمنا في مجال تطوير المنتجات الألياف الجديدة، والمواد المضافة، وتقنيات التصنيع، بالإضافة إلى تطوير الأوراق المتخصصة، والدرجات المخصصة، ومنتجات الورق المرتبطة بالتغليف. ويمكن أن يمتد الدعم من مرحلة تطوير الفكرة إلى مرحلة الإنتاج التجريبي، وذلك بحسب متطلبات كل مشروع.'],
                       ['تحسين العمليات وكفاءة المصانع', 'ندعم مصنّعي اللب والورق من خلال تحسين العمليات والتشغيل، مع التركيز على تحديد الاختناقات، وأوجه القصور في كفاءة استخدام الطاقة، وفجوات العمليات، والهدر في الإنتاج، وضعف أداء المعدات. وقد تشمل حلولنا الأتمتة، والمراقبة في الوقت الفعلي، وتحسين سير العمل.'],
                       ['حلول الورق المسترجع وإعادة التدوير', 'عمليات الجمع والفرز وإزالة الملوثات والمعالجة لاستعادة الورق المسترجع كمادة خام قابلة للاستخدام، بما يسهم في استخدام أكثر كفاءة للمواد وتعزيز ممارسات إعادة التدوير.'],
                       ['معالجة مياه الصرف الصحي', 'المعالجة البيولوجية، والجرعات الكيميائية، والترشيح، ومعالجة الحمأة، بما يتناسب مع خصائص مياه الصرف في كل منشأة، مع الدعم في التركيب والتشغيل التجريبي ومراقبة الأداء.'],
                       ['التدريب التقني', 'برامج تدريبية مخصصة يقدّمها خبراء محليون ودوليون، تشمل تشغيل الآلات، والتحكم في العمليات، وضمان الجودة، والصيانة، والسلامة، من خلال ورش عمل وجلسات تطبيقية.'],
                       ['خدمات ما بعد البيع وقطع الغيار والدعم الفني', 'بالنسبة للمعدات والأنظمة المورّدة ضمن حلولنا، يمكن أن يمتد الدعم إلى ما بعد التركيب: المساعدة الفنية، وصيانة المعدات، ودعم الأداء، ومتطلبات قطع الغيار، حيثما ينطبق ذلك على نطاق المشروع.']]},
            type='cards', tone='soft'),
        pp('Turnkey Projects — From Idea to Execution', 'Complete Project Support for Pulp & Paper',
           ['Gulf Industrial Solutions supports turnkey pulp and paper projects from initial consultation and concept development through implementation and handover.', 'Project support can include:'],
           'مشروعات متكاملة — من الفكرة إلى التنفيذ', 'دعم متكامل للمشروعات في قطاع اللب والورق',
           ['تدعم الخليج للحلول الصناعية مشروعات اللب والورق المتكاملة، بدءًا من الاستشارات الأولية وتطوير الفكرة وصولًا إلى التنفيذ والتسليم.', 'وقد يشمل دعم المشروع:'],
           image='pulp-turnkey', flip=True,
           en_tags='Technology Selection | Plant Design | Equipment Procurement | Installation | Testing | Commissioning',
           ar_tags='اختيار التكنولوجيا | تصميم المصنع | توريد المعدات | التركيب | الاختبار | التشغيل التجريبي',
           en_after=['We also support individual equipment requirements and production upgrades according to the project scope.'],
           ar_after=['كما ندعم متطلبات المعدات الفردية وترقيات الإنتاج وفقًا لنطاق المشروع.']),
        sec({'eyebrow': 'Why Choose Gulf Industrial Solutions', 'title': 'Technical Expertise Across the Paper Production Process',
             'cards': [['Industry-Focused Solutions', 'Solutions covering pulp, paper, tissue, and board production requirements.'],
                       ['Integrated Capabilities', 'From project planning and equipment selection to optimisation, quality control, and technical support.'],
                       ['Equipment & Process Knowledge', 'Support across stock preparation, paper machines, finishing, chemicals, recycling, and related processes.'],
                       ['Flexible Project Scope', 'Support ranging from individual equipment requirements to complete turnkey projects.']]},
            {'eyebrow': 'لماذا تختارون الخليج للحلول الصناعية', 'title': 'خبرة تقنية تغطي كامل عملية إنتاج الورق',
             'cards': [['حلول تركز على احتياجات القطاع', 'حلول تغطي متطلبات إنتاج اللب والورق والمناديل والكرتون.'],
                       ['قدرات متكاملة', 'من تخطيط المشاريع واختيار المعدات إلى تحسين العمليات ومراقبة الجودة والدعم الفني.'],
                       ['معرفة بالمعدات والعمليات', 'دعم يشمل تحضير اللب، وآلات الورق، والتشطيب، والمواد الكيميائية، وإعادة التدوير، والعمليات ذات الصلة.'],
                       ['مرونة في نطاق المشروع', 'دعم يتراوح بين متطلبات المعدات الفردية والمشروعات المتكاملة بنظام تسليم المفتاح.']]},
            type='cards'),
        CTA,
    ]}

# ---------------------------------------------------------------- Corrugated
PAGES['corrugated'] = {
    'slug': 'corrugated-packaging', 'hero_image': 'corrugated-hero',
    'en': {'nav': 'Corrugated Packaging', 'eyebrow': 'Corrugated Packaging', 'title': 'Complete Solutions for Corrugated Packaging Production',
           'line': 'From Concept to Production'},
    'ar': {'nav': 'التغليف المموج', 'eyebrow': 'تغليف الكرتون المموج', 'title': 'حلول متكاملة لإنتاج تغليف الكرتون المموج',
           'line': 'من الفكرة إلى الإنتاج'},
    'sections': [
        sec({'eyebrow': 'Our Corrugated Packaging Capabilities', 'title': 'Equipment & Solutions Across the Production Process',
             'body': ['Our capabilities span key stages of corrugated board and packaging production, including:'],
             'list': ['Corrugated Board Production Lines', 'Single Facers & Double Facers', 'Pre-Heaters / Pre-Conditioners', 'Mill Roll Stands',
                      'Slitter Scorers', 'Rotary Shears', 'Stackers & Conveyor Systems', 'Printing Machines', 'Stitching Machines',
                      'Gluing Machines', 'Automatic Starch Kitchen Systems', 'Water-Repellent Agents', 'Starch Additives',
                      'Paper & Box Testing Equipment', 'Waste Baling Presses'],
             'after': ['These solutions support both individual equipment requirements and complete corrugated production projects.']},
            {'eyebrow': 'قدراتنا في مجال تغليف الكرتون المموج', 'title': 'معدات وحلول لجميع مراحل الإنتاج',
             'body': ['تغطي قدراتنا المراحل الرئيسية لإنتاج الكرتون المموج والتغليف، وتشمل:'],
             'list': bullets('• خطوط إنتاج الكرتون المموج• Single Facers & Double Facers• أجهزة التسخين المسبق / التكييف المسبق• Mill Roll Stands• Slitter Scorers• Rotary Shears• أنظمة التكديس والسيور الناقلة• آلات الطباعة• آلات التدبيس• آلات اللصق• أنظمة مطبخ النشا الأوتوماتيكية• مواد مقاومة للماء• إضافات النشا• معدات فحص الورق والصناديق• مكابس كبس النفايات'),
             'after': ['توفر هذه الحلول الدعم لكل من متطلبات المعدات الفردية والمشاريع المتكاملة لإنتاج الكرتون المموج.']},
            type='list', tone='soft'),
        pp('Corrugated Board Production Lines', 'Production Solutions for Corrugated Board Manufacturing',
           ['Our corrugated production lines support efficient and consistent board manufacturing, with production speeds ranging from 150 m/min to 400 m/min.',
            'The production line covers key stages from corrugation to sheet cutting and stacking, ensuring consistent production and board quality.', 'Key Equipment'],
           'خطوط إنتاج الكرتون المموج', 'حلول إنتاجية لتصنيع الكرتون المموج',
           ['توفر خطوط الإنتاج لدينا حلولًا فعالة ومتسقة لتصنيع الكرتون المموج، بسرعات إنتاج تتراوح بين 150 و400 متر في الدقيقة.',
            'يغطي خط الإنتاج المراحل الرئيسية بدءًا من تشكيل التمويج وصولًا إلى تقطيع الألواح وتكديسها، بما يضمن استمرارية الإنتاج وجودة الألواح.', 'المعدات الرئيسية'],
           image='corrugated-line',
           en_tags='Single Facer | Double Facer | Pre-Heater | Mill Roll Stand | Slitter Scorer | Rotary Shear | Stacker',
           ar_tags='Single Facer | Double Facer | Pre-Heater | Mill Roll Stand | Slitter Scorer | Rotary Shear | Stacker'),
        pp('Single Facer & Double Facer', 'Equipment for Corrugated Board Formation',
           ['Single-facer and double-facer machines support different stages of corrugated board production.',
            'The single facer produces single-face corrugated board, while the double facer combines layers of single-face corrugated board to form a stronger, multi-layer corrugated sheet.',
            'These systems support consistent corrugation, board strength, and production stability.'],
           'وحدات التبطين أحادية الوجه وثنائية الوجه', 'معدات تشكيل الكرتون المضلع',
           ['تقوم آلتا Single Facer وDouble Facer بمعالجة مراحل مختلفة من عملية إنتاج الكرتون المضلع.',
            'تنتج Single Facer الكرتون المضلع أحادي الوجه، بينما تقوم Double Facer بدمج طبقات من الكرتون المضلع أحادي الوجه لتكوين لوح كرتون مضلع أقوى ومتعدد الطبقات.',
            'تضمن هذه الأنظمة اتساق عملية التخديد، وقوة الألواح، واستقرار الإنتاج.'],
           image='corrugated-facer', flip=True),
        sec({'eyebrow': 'Pre-Heaters, Mill Roll Stands, Slitter Scorers & Stackers', 'title': 'Controlled Feed, Precision Cutting and Stacking',
             'cards': [['Pre-Heaters / Pre-Conditioners', 'Pre-heaters uniformly heat paper or board to support moisture absorption and adhesive bonding. Temperature and moisture control help prepare the material for subsequent processing.'],
                       ['Mill Roll Stands', 'Mill roll stands support paper rolls during production, providing controlled loading, unwinding, tension, braking, and alignment for continuous material feed into the corrugating process.'],
                       ['Slitter Scorers', 'Designed for accurate cutting and scoring of corrugated sheets, supporting clean cuts, easy folding, high-speed production, and reduced material waste.'],
                       ['Rotary Shears', 'Provide precise cutting of paper and cardboard rolls, including roll sizing and edge trimming.'],
                       ['Stackers', 'Handle and align finished corrugated sheets or boxes, with adjustable stacking height and compression according to production requirements.']]},
            {'eyebrow': 'أجهزة التسخين المسبق وحوامل البكرات وآلات الشق والتكديس', 'title': 'تغذية متحكم بها وقص وتكديس بدقة',
             'cards': [['أجهزة التسخين المسبق / التكييف المسبق', 'تعمل أجهزة التسخين المسبق على تسخين الورق أو الكرتون بشكل متجانس، بما يساعد على امتصاص الرطوبة وتحسين التصاق المواد اللاصقة. ويساعد التحكم في درجة الحرارة والرطوبة على تهيئة المواد لمراحل المعالجة اللاحقة.'],
                       ['حوامل بكرات الورق (Mill Roll Stands)', 'تدعم حوامل بكرات الورق بكرات الورق أثناء الإنتاج، وتوفر تحكمًا في عمليات التحميل وفك اللف وشد الورق والكبح والمحاذاة، بما يضمن تغذية مستمرة للمواد إلى عملية تشكيل الكرتون المموج.'],
                       ['Slitter Scorers', 'مصممة للقص والتخديد الدقيق لألواح الكرتون المضلع، بما يدعم الحصول على قصات نظيفة، وسهولة الطي، وإنتاجًا عالي السرعة، وتقليل هدر المواد.'],
                       ['Rotary Shears', 'توفر قصًا دقيقًا لبكرات الورق والكرتون، بما في ذلك تقطيع البكرات إلى المقاسات المطلوبة وتشذيب الحواف.'],
                       ['Stackers', 'تتولى مناولة ومحاذاة ألواح الكرتون المضلع أو الصناديق النهائية، مع إمكانية ضبط ارتفاع التكديس ومستوى الضغط وفقًا لمتطلبات الإنتاج.']]},
            type='cards', tone='soft'),
        pp('Printing, Converting & Finishing', 'Solutions for Corrugated Packaging Production',
           ['We provide equipment for key printing and converting operations, including:'],
           'الطباعة والتحويل والتشطيب', 'حلول لإنتاج تغليف الكرتون المموج',
           ['نوفّر معدات للعمليات الرئيسية للطباعة والتحويل، وتشمل:'],
           image='corrugated-printing',
           en_tags='Printing | Stitching | Glue Application | Cutting | Scoring | Finishing',
           ar_tags='الطباعة | التدبيس | تطبيق المواد اللاصقة | القص | التخديش | التشطيب',
           en_after=['Printing machines support accurate graphics, logos, and product information, while stitching and glue machines provide closure and bonding solutions for corrugated packaging.',
                     'Glue systems support both hot-melt and cold-glue applications, with controlled and uniform adhesive application.'],
           ar_after=['تدعم آلات الطباعة الحصول على رسومات وشعارات ومعلومات عن المنتج بدقة، بينما توفر آلات التدبيس واللصق حلولًا لإغلاق وربط عبوات الكرتون المموج.',
                     'تدعم أنظمة اللصق استخدام المواد اللاصقة الساخنة والباردة، مع تطبيق متحكم به ومتجانس للمادة اللاصقة.']),
        pp('Auto Starch Kitchen & Adhesive Solutions', 'Supporting Consistent Adhesive Preparation',
           ['Our Auto Starch Kitchen Systems provide automated starch preparation with controlled measurement and mixing.',
            'The system supports consistent adhesive quality, reduces manual handling, and helps maintain bonding strength in corrugated board production.',
            'Our starch additives enhance adhesive performance through improvements in:'],
           'أنظمة مطبخ النشا وحلول المواد اللاصقة', 'دعم تحضير المواد اللاصقة بشكل متسق',
           ['توفر أنظمة مطبخ النشا الأوتوماتيكية لدينا تحضيرًا آليًا للنشا مع التحكم في القياس والخلط.',
            'ويدعم النظام ثبات جودة المواد اللاصقة، ويقلل من المناولة اليدوية، ويساعد في الحفاظ على قوة الترابط أثناء إنتاج الكرتون المموج.',
            'وتعزز إضافات النشا لدينا أداء المواد اللاصقة من خلال تحسين:'],
           image='corrugated-starch', flip=True,
           en_tags='Bonding Strength | Viscosity Control | Water Resistance',
           ar_tags='قوة الترابط | التحكم في اللزوجة | مقاومة الماء',
           en_after=['Solutions can be customised according to specific production requirements.'],
           ar_after=['يمكن تخصيص الحلول وفقًا لمتطلبات الإنتاج المحددة.']),
        sec({'eyebrow': 'Board performance, testing & waste', 'title': 'Supporting quality from board to bale',
             'cards': [['Water-Repellent Agents & Starch Additives', 'Water-repellent agents are applied during manufacturing to help reduce moisture absorption in paper and corrugated packaging, reducing the risk of warping, weakening, and material deterioration. Starch additives support adhesive performance and can be selected according to bonding and process requirements.'],
                       ['Quality Control & Testing Equipment', 'Paper and box testing solutions evaluate key packaging performance parameters — bursting strength, compression and moisture — helping manufacturers monitor material quality, production consistency, and packaging performance during handling and transportation.'],
                       ['Waste Handling & Baling Solutions', 'Our Waste Baling Presses compress and bale production waste such as trimmings and scrap, supporting more efficient storage, handling, and recycling while helping optimise space within the production facility.']]},
            {'eyebrow': 'أداء الألواح والاختبار والنفايات', 'title': 'دعم الجودة من اللوح إلى البالة',
             'cards': [['عوامل مقاومة الماء وإضافات النشا', 'تُستخدم عوامل مقاومة الماء أثناء التصنيع للمساعدة في تقليل امتصاص الرطوبة في الورق وتغليف الكرتون المموج، وتقليل مخاطر الالتواء وضعف المواد وتدهورها. وتدعم إضافات النشا أداء المواد اللاصقة، ويمكن اختيارها وفقًا لمتطلبات الترابط والمعالجة.'],
                       ['معدات مراقبة الجودة والاختبار', 'تدعم حلولنا لاختبار الورق والصناديق تقييم معايير الأداء الرئيسية: قوة الانفجار، ومقاومة الضغط، والرطوبة، بما يساعد المصنّعين على مراقبة جودة المواد واتساق الإنتاج وأداء مواد التغليف أثناء المناولة والنقل.'],
                       ['حلول التعامل مع النفايات وكبسها', 'تقوم مكابس كبس النفايات لدينا بضغط وكبس مخلفات الإنتاج مثل القصاصات والمخلفات، بما يحقق تخزينًا ومناولة وإعادة تدوير أكثر كفاءة، مع تحسين استغلال المساحة داخل منشأة الإنتاج.']]},
            type='cards'),
        sec({'eyebrow': 'Applications', 'title': 'Supporting Corrugated Packaging Production',
             'body': ['Our equipment and solutions can support requirements across:'],
             'list': ['Corrugated Board Manufacturing', 'Carton & Box Production', 'Printing & Packaging Operations', 'Corrugated Converting',
                      'Paper & Board Processing', 'Packaging Quality Control', 'Production Waste Handling'],
             'after': ['Solutions can be provided according to the equipment requirement, production process, and project scope.']},
            {'eyebrow': 'التطبيقات', 'title': 'دعم إنتاج تغليف الكرتون المموج',
             'body': ['يمكن لمعداتنا وحلولنا دعم المتطلبات في المجالات التالية:'],
             'list': bullets('• تصنيع الكرتون المموج• إنتاج الكرتون والصناديق• عمليات الطباعة والتغليف• تحويل الكرتون المموج• معالجة الورق والكرتون• مراقبة جودة مواد التغليف• التعامل مع مخلفات الإنتاج'),
             'after': ['يمكن توفير الحلول وفقًا لمتطلبات المعدات، وعملية الإنتاج، ونطاق المشروع.']},
            type='list', tone='soft'),
        pp('From Equipment Supply to Complete Projects', 'From Individual Equipment to Complete Production Solutions',
           ['Gulf Industrial Solutions supports customers with both individual equipment requirements and complete corrugated packaging production solutions.', 'Our project support covers:'],
           'من توريد المعدات إلى المشاريع المتكاملة', 'من المعدات الفردية إلى حلول الإنتاج المتكاملة',
           ['تدعم الخليج للحلول الصناعية العملاء في تلبية متطلبات المعدات الفردية، بالإضافة إلى حلول الإنتاج المتكاملة لتغليف الكرتون المموج.', 'ويشمل دعمنا للمشروعات:'],
           image='corrugated-projects', flip=True,
           en_tags='Consultation | Equipment | Installation | Commissioning | Technical Support',
           ar_tags='الاستشارات | المعدات | التركيب | التشغيل التجريبي | الدعم الفني',
           en_after=['Solutions are structured around the production requirements and technical scope of each project.'],
           ar_after=['تُصمَّم الحلول وفقًا لمتطلبات الإنتاج والنطاق الفني لكل مشروع.']),
        sec({'eyebrow': 'Why Choose Gulf Industrial Solutions', 'title': 'Corrugated Packaging Solutions Built Around Your Requirements',
             'cards': [['Industry-Focused Solutions', 'Equipment and technical solutions covering key stages of corrugated production.'],
                       ['Integrated Equipment Range', 'From board production and converting to testing, adhesive systems, and waste handling.'],
                       ['Production-Focused Approach', 'Solutions selected according to production requirements, operating conditions, and customer specifications.'],
                       ['From Equipment to Projects', 'Support for individual equipment requirements as well as complete production solutions.']]},
            {'eyebrow': 'لماذا تختارون الخليج للحلول الصناعية', 'title': 'حلول تغليف الكرتون المموج وفقًا لمتطلباتكم',
             'cards': [['حلول متخصصة في القطاع', 'معدات وحلول فنية تغطي المراحل الرئيسية لإنتاج الكرتون المموج.'],
                       ['مجموعة متكاملة من المعدات', 'من إنتاج الألواح والتحويل إلى الاختبار، وأنظمة المواد اللاصقة، والتعامل مع النفايات.'],
                       ['نهج يركز على الإنتاج', 'حلول تُختار وفقًا لمتطلبات الإنتاج، وظروف التشغيل، ومواصفات العميل.'],
                       ['من المعدات إلى المشاريع', 'دعم لمتطلبات المعدات الفردية، بالإضافة إلى حلول الإنتاج المتكاملة.']]},
            type='cards'),
        CTA,
    ]}

# ---------------------------------------------------------------- Water
CHEM_EN = ['Oxygen Scavengers', 'Phosphates', 'Polymers', 'Alkalinity Builders', 'Defoamers', 'Sludge Conditioners',
           'Condensate Treatment Chemicals', 'Scale and Corrosion Inhibitors', 'RO Antiscalants', 'Biocides', 'pH Adjusters',
           'Cleaning Agents', 'Disinfectants']
BOILER = ['Oxygen Scavengers', 'Phosphate Residual Programs', 'Polymer Programs', 'Alkalinity Builders', 'Defoamers',
          'Sludge Conditioners', 'Condensate Treatments', 'Filming, Neutralising & Combined Amines', 'pH Correction']
PAGES['water'] = {
    'slug': 'water-wastewater-treatment', 'hero_image': 'water-hero',
    'en': {'nav': 'Water & Wastewater', 'eyebrow': 'Water & Wastewater Treatment Solutions', 'title': 'Complete Solutions for Water & Wastewater Treatment',
           'line': 'From Treatment Requirements to Plant Operation',
           'text': 'From treatment programs and chemicals to wastewater treatment processes and RO plant treatment, our solutions are based on specific water quality, process, and operational requirements.'},
    'ar': {'nav': 'المياه ومياه الصرف', 'eyebrow': 'حلول معالجة المياه ومياه الصرف الصناعي', 'title': 'حلول متكاملة لمعالجة المياه ومياه الصرف الصناعي',
           'line': 'من متطلبات المعالجة إلى تشغيل المحطة',
           'text': 'بدءًا من برامج ومواد المعالجة الكيميائية، وصولًا إلى عمليات معالجة مياه الصرف ومعالجة مياه محطات التناضح العكسي، تُبنى حلولنا وفقًا لخصائص جودة المياه، ومتطلبات العمليات، والظروف التشغيلية.'},
    'sections': [
        sec({'eyebrow': 'Our Water & Wastewater Capabilities', 'title': 'Solutions for Industrial Water Treatment',
             'body': ['Our solutions cover key water and wastewater treatment requirements, including:'],
             'list': ['Process Water Treatment', 'Boiler Water Treatment', 'Cooling Water Treatment', 'Wastewater Treatment Plants & Chemicals',
                      'Reverse Osmosis Treatment', 'Chemical Cleaning', 'Water Treatment Chemicals', 'Desalination & Related Water Treatment Processes']},
            {'eyebrow': 'قدراتنا في مجال معالجة المياه ومياه الصرف الصناعي', 'title': 'حلول لمعالجة المياه الصناعية',
             'body': ['تغطي حلولنا أهم متطلبات معالجة المياه ومياه الصرف الصناعي، وتشمل:'],
             'list': bullets('• معالجة مياه العمليات الصناعية• معالجة مياه الغلايات• معالجة مياه التبريد• محطات معالجة مياه الصرف والمواد الكيميائية المستخدمة فيها• معالجة المياه بالتناضح العكسي• التنظيف الكيميائي• المواد الكيميائية لمعالجة المياه• التحلية وعمليات معالجة المياه ذات الصلة')},
            type='list', tone='soft'),
        pp('Process Water Treatment', 'Treatment Solutions for Industrial Water Systems',
           ['We provide process water treatment programs and chemicals for a range of industrial applications, including:'],
           'معالجة مياه العمليات الصناعية', 'حلول معالجة المياه للأنظمة الصناعية',
           ['نقدم برامج ومواد كيميائية لمعالجة مياه العمليات الصناعية لمجموعة من التطبيقات الصناعية، بما في ذلك:'],
           image='water-process',
           en_list=['Open evaporative and closed cooling water systems', 'Boiler water treatment', 'Refinery treatment programs',
                    'Fertilizer and chemical process industries', 'Power generation', 'Steel and metal process industries',
                    'Pharmaceutical and food industries', 'Potable water treatment', 'Pretreatment and wastewater treatment',
                    'Swimming pool applications', 'Desalination and related processes'],
           ar_list=bullets('• أنظمة مياه التبريد المفتوحة بالتبخر والمغلقة• معالجة مياه الغلايات• برامج معالجة مياه المصافي• صناعات الأسمدة والصناعات الكيميائية• توليد الطاقة• صناعات الحديد والصلب والمعادن• الصناعات الدوائية والغذائية• معالجة مياه الشرب• المعالجة الأولية ومعالجة مياه الصرف• تطبيقات أحواض السباحة• التحلية والعمليات ذات الصلة'),
           en_after=['Our solutions also include online and offline chemical cleaning, as well as reverse osmosis antiscalants and biocontrol agents.'],
           ar_after=['تشمل حلولنا أيضًا التنظيف الكيميائي داخل الخط وخارجه، بالإضافة إلى مضادات الترسب المستخدمة في أنظمة التناضح العكسي، ومواد المكافحة الحيوية.']),
        pp('Boiler Water Treatment', 'Chemical Solutions for Boiler Systems',
           ['Gulf Industrial Solutions provides treatment products for boiler systems ranging from low-pressure steam generators to high-pressure water tube systems.', 'Our solutions include:'],
           'معالجة مياه الغلايات', 'حلول كيميائية لأنظمة الغلايات',
           ['توفر الخليج للحلول الصناعية منتجات معالجة لأنظمة الغلايات، بدءًا من مولدات البخار منخفضة الضغط وحتى أنظمة الغلايات ذات الأنابيب المائية عالية الضغط.', 'تشمل حلولنا:'],
           image='water-boiler', flip=True, en_list=BOILER, ar_list=BOILER,
           en_after=['These treatment programs address different boiler and condensate treatment requirements according to system conditions.'],
           ar_after=['تعالج هذه البرامج مختلف متطلبات معالجة مياه الغلايات والمكثفات وفقًا لظروف كل نظام.']),
        pp('Cooling Water Treatment', 'Supporting Cooling Tower Performance',
           ['We provide chemical solutions for cooling tower systems, including pre-commission cleaning, flushing, and passivation.', 'Our inhibitor solutions are designed to help control:'],
           'معالجة مياه التبريد', 'دعم أداء أبراج التبريد',
           ['نوفر حلولًا كيميائية لأنظمة أبراج التبريد، بما في ذلك التنظيف قبل التشغيل، والغسيل، والتخميل.', 'صُممت مثبطاتنا للمساعدة في التحكم في:'],
           image='water-cooling', en_tags='Scale | Corrosion | Fouling', ar_tags='Scale | Corrosion | Fouling',
           en_after=['These treatment programs support the ongoing water treatment requirements of cooling tower systems.'],
           ar_after=['تدعم برامج المعالجة هذه متطلبات معالجة المياه المستمرة لأنظمة أبراج التبريد.']),
        pp('Wastewater Treatment Plants & Chemicals', 'Treatment Processes for Industrial Wastewater',
           ['Gulf Industrial Solutions provides wastewater treatment solutions using physical, chemical, and biological treatment processes, according to the type and concentration of pollutants present in the wastewater.', 'Treatment solutions may include:'],
           'محطات ومواد معالجة مياه الصرف الصناعي', 'عمليات معالجة مياه الصرف الصناعي',
           ['توفر الخليج للحلول الصناعية حلولًا لمعالجة مياه الصرف باستخدام عمليات المعالجة الفيزيائية والكيميائية والبيولوجية، وفقًا لنوع الملوثات الموجودة في مياه الصرف وتركيزها.', 'قد تشمل حلول المعالجة:'],
           image='water-wastewater', flip=True,
           en_list=['Physical Treatment', 'Chemical Treatment', 'Biological Treatment', 'Aerobic Treatment', 'Anaerobic Treatment',
                    'Oil-Water Separation', 'Physicochemical Treatment', 'Dissolved Air Flotation (DAF)', 'Disinfection'],
           ar_list=bullets('المعالجة الفيزيائية• المعالجة الكيميائية• المعالجة البيولوجية• المعالجة الهوائية• المعالجة اللاهوائية• فصل الزيت عن الماء• المعالجة الفيزيوكيميائية• التعويم بالهواء المذاب (DAF)• التطهير'),
           en_after=['Our wastewater treatment plants cater to applications requiring different treatment processes, with treated water intended for appropriate discharge or reuse applications.'],
           ar_after=['تلبي محطات معالجة مياه الصرف لدينا متطلبات التطبيقات المختلفة التي تتطلب عمليات معالجة متنوعة، مع تخصيص المياه المعالجة للتصريف أو إعادة استخدامها في التطبيقات المناسبة.']),
        sec({'eyebrow': 'Reverse Osmosis Treatment', 'title': 'Supporting RO Plant Operation & Maintenance',
             'body': ['Reverse osmosis plants require appropriate chemical treatment for operation and maintenance. Our RO treatment solutions include:'],
             'cards': [['Antiscalants', 'To help control scale and mineral deposits on RO membranes.'],
                       ['Biocides', 'To control biological growth that can contribute to membrane fouling.'],
                       ['pH Adjusters', 'To maintain suitable pH conditions for RO membrane operation.'],
                       ['Cleaning Agents', 'For membrane cleaning and removal of fouling and scale buildup.'],
                       ['Disinfectants', 'For system disinfection and microbial control.']],
             'after': ['We provide both online and offline chemical cleaning solutions, along with treatment chemicals for process water, boiler systems, cooling towers, wastewater, and RO applications.']},
            {'eyebrow': 'معالجة التناضح العكسي', 'title': 'دعم تشغيل وصيانة محطات التناضح العكسي',
             'body': ['تتطلب محطات التناضح العكسي معالجة كيميائية مناسبة للتشغيل والصيانة. تشمل حلولنا لمعالجة التناضح العكسي:'],
             'cards': [['مضادات الترسب', 'للمساعدة في التحكم في الترسبات والرواسب المعدنية على أغشية التناضح العكسي.'],
                       ['المبيدات الحيوية', 'للتحكم في النمو البيولوجي الذي قد يسهم في تلوث الأغشية وانسدادها.'],
                       ['مواد ضبط الأس الهيدروجيني', 'للحفاظ على مستويات مناسبة للأس الهيدروجيني لتشغيل أغشية التناضح العكسي.'],
                       ['مواد التنظيف', 'لتنظيف الأغشية وإزالة التلوث والترسبات المتراكمة.'],
                       ['المطهرات', 'لتطهير النظام والسيطرة على الميكروبات.']],
             'after': ['نوفر حلول التنظيف الكيميائي أثناء التشغيل وخارج التشغيل، إلى جانب مواد المعالجة الكيميائية لمياه العمليات، وأنظمة الغلايات، وأبراج التبريد، ومياه الصرف الصناعي، وتطبيقات التناضح العكسي.']},
            type='cards', tone='soft', image='water-ro'),
        pp('Filtration & Water Treatment Systems', 'Filtration and Treatment for Industrial Water Applications',
           ['Filtration is an important part of water and wastewater treatment, particularly where suspended solids and other contaminants need to be separated before further treatment or reuse.',
            'Our water treatment capabilities include filtration processes used as part of physical treatment and pretreatment requirements.'],
           'أنظمة الترشيح ومعالجة المياه', 'الترشيح والمعالجة للتطبيقات الصناعية لمعالجة المياه',
           ['تُعد عملية الترشيح جزءًا مهمًا من معالجة المياه ومياه الصرف الصناعي، خاصةً في الحالات التي تتطلب فصل المواد الصلبة العالقة والملوثات الأخرى قبل مراحل المعالجة اللاحقة أو إعادة الاستخدام.',
            'تشمل قدراتنا في معالجة المياه عمليات الترشيح المستخدمة كجزء من متطلبات المعالجة الفيزيائية والمعالجة الأولية.'],
           image='water-filtration'),
        pp('Water Treatment Chemicals & Chemical Cleaning', 'Chemical Solutions for Water Treatment Systems',
           ['We provide chemical treatment solutions for different industrial water applications, including boiler, cooling tower, process water, wastewater and RO systems.', 'Chemical solutions include:'],
           'المواد الكيميائية لمعالجة المياه والتنظيف الكيميائي', 'حلول كيميائية لأنظمة معالجة المياه',
           ['نوفر حلول معالجة كيميائية لمختلف تطبيقات المياه الصناعية، بما في ذلك أنظمة الغلايات، وأبراج التبريد، ومياه العمليات، ومياه الصرف الصناعي، وأنظمة التناضح العكسي.', 'تشمل الحلول الكيميائية:'],
           image='water-chemicals', flip=True, en_tags=' | '.join(CHEM_EN), ar_tags=' | '.join(CHEM_EN),
           en_after=['Chemical cleaning services include both online and offline chemical cleaning.'],
           ar_after=['تشمل خدمات التنظيف الكيميائي التنظيف أثناء التشغيل والتنظيف خارج التشغيل.']),
        sec({'eyebrow': 'Projects & support', 'title': 'From Treatment Requirements to Project Execution',
             'cards': [['Turnkey Water & Wastewater Projects', "For projects requiring more than individual treatment products or chemicals, Gulf Industrial Solutions can deliver water and wastewater requirements as complete project solutions — including design, equipment supply, installation, commissioning, and maintenance, tailored to each project's scope."],
                       ['Technical Training & Support', 'Technical training and support are provided to help ensure the correct understanding and application of water treatment solutions, chemicals and treatment processes.']]},
            {'eyebrow': 'المشاريع والدعم', 'title': 'من متطلبات المعالجة إلى تنفيذ المشروع',
             'cards': [['مشاريع المياه ومياه الصرف الصناعي بنظام تسليم المفتاح', 'بالنسبة للمشاريع التي تتطلب أكثر من مجرد منتجات أو مواد كيميائية فردية للمعالجة، يمكن للخليج للحلول الصناعية تقديم متطلبات المياه ومياه الصرف الصناعي كحلول مشاريع متكاملة تشمل التصميم، وتوريد المعدات، والتركيب، والتشغيل، والصيانة، وفقًا لنطاق كل مشروع.'],
                       ['التدريب والدعم الفني', 'يتم تقديم التدريب والدعم الفني للمساعدة في ضمان الفهم الصحيح والتطبيق السليم لحلول معالجة المياه، والمواد الكيميائية، وعمليات المعالجة.']]},
            type='cards'),
        sec({'eyebrow': 'Applications', 'title': 'Water Treatment Across Industrial Sectors',
             'body': ['Our water and wastewater treatment solutions support applications including:'],
             'list': ['Refineries', 'Fertilizer & Chemical Processing', 'Power Generation', 'Steel & Metal Processing',
                      'Pharmaceutical & Food Industries', 'Industrial Water Systems', 'Potable Water Applications', 'Desalination', 'Swimming Pool Applications']},
            {'eyebrow': 'التطبيقات', 'title': 'معالجة المياه في مختلف القطاعات الصناعية',
             'body': ['تدعم حلولنا لمعالجة المياه ومياه الصرف الصناعي تطبيقات تشمل:'],
             'list': bullets('• المصافي• الأسمدة والصناعات الكيميائية• توليد الطاقة• صناعات الحديد والصلب والمعادن• الصناعات الدوائية والغذائية• أنظمة المياه الصناعية• تطبيقات مياه الشرب• التحلية• تطبيقات حمامات السباحة')},
            type='list', tone='soft'),
        sec({'eyebrow': 'Why Choose Gulf Industrial Solutions', 'title': 'Industrial water expertise, application-focused',
             'cards': [['Industrial Water Expertise', 'Solutions covering process water, boiler, cooling, wastewater and RO applications.'],
                       ['Chemical Treatment Capability', 'A range of treatment chemicals for different industrial water systems.'],
                       ['Application-Focused Solutions', 'Treatment approaches based on specific process and water requirements.'],
                       ['From Treatment to Project Requirements', 'Support across individual treatment needs and broader water and wastewater requirements.']]},
            {'eyebrow': 'لماذا تختارون الخليج للحلول الصناعية', 'title': 'خبرة في المياه الصناعية تركز على التطبيق',
             'cards': [['خبرة في معالجة المياه الصناعية', 'حلول تغطي مياه العمليات، والغلايات، والتبريد، ومياه الصرف الصناعي، وتطبيقات التناضح العكسي.'],
                       ['قدرات المعالجة الكيميائية', 'مجموعة من المواد الكيميائية لمعالجة المياه لمختلف أنظمة المياه الصناعية.'],
                       ['حلول تركز على التطبيق', 'أساليب معالجة تُبنى وفقًا لمتطلبات العمليات والمياه المحددة.'],
                       ['من المعالجة إلى متطلبات المشاريع', 'دعم يشمل احتياجات المعالجة الفردية والمتطلبات الأوسع للمياه ومياه الصرف الصناعي.']]},
            type='cards'),
        CTA,
    ]}

# ---------------------------------------------------------------- Rental
PAGES['rental'] = {
    'slug': 'rental-services', 'hero_image': 'rental-hero',
    'en': {'nav': 'Rental Services', 'eyebrow': 'Rental Services', 'title': 'Heavy Equipment Rental for Industrial & Construction Projects',
           'line': 'Equipment When You Need It',
           'text': 'Our rental services provide access to a range of equipment for projects requiring reliable machinery without the upfront investment associated with equipment ownership.'},
    'ar': {'nav': 'خدمات التأجير', 'eyebrow': 'خدمات التأجير', 'title': 'تأجير المعدات الثقيلة للمشاريع الصناعية والإنشائية',
           'line': 'المعدات عند الحاجة إليها',
           'text': 'تتيح خدمات التأجير لدينا الوصول إلى مجموعة من المعدات للمشاريع التي تتطلب معدات موثوقة، دون الحاجة إلى الاستثمار المسبق المرتبط بامتلاك المعدات.'},
    'sections': [
        pp('Rental Services Overview', 'Supporting Construction & Industrial Operations',
           ['Gulf Industrial Solutions provides heavy equipment rental solutions for construction, industrial, infrastructure, and site development requirements.',
            'We provide flexible heavy equipment rental solutions for different project and operational requirements.',
            'Our equipment can support activities ranging from construction and excavation to road development, mining, industrial site development, and waste management.'],
           'نظرة عامة على خدمات التأجير', 'دعم عمليات البناء والصناعة',
           ['توفر الخليج للحلول الصناعية حلول تأجير المعدات الثقيلة لمشاريع البناء والصناعة والبنية التحتية وتطوير المواقع.',
            'نوفر حلول تأجير مرنة للمعدات الثقيلة لمختلف متطلبات المشاريع والتشغيل.',
            'تدعم معداتنا مجموعة من الأنشطة، بدءًا من البناء والحفر، وصولًا إلى تطوير الطرق، والتعدين، وتطوير المواقع الصناعية، وإدارة النفايات.'],
           image='rental-overview'),
        sec({'eyebrow': 'Equipment Available', 'title': 'Our Heavy Equipment Fleet',
             'fleet': [['Backhoe Loaders', 'JCB 4CX Super Backhoe Loader · JCB Backhoe Loader', 'rental-backhoe'],
                       ['Telescopic Handlers', 'JCB 540-170 Telescopic Handler', 'rental-telehandler'],
                       ['Scissor Lifts', '10–14 Meter Scissor Lifts', 'rental-scissor'],
                       ['Forklifts', '3–16 Ton Forklifts · TCM 10 Ton Diesel Forklift · ZOOMLION Forklifts', 'rental-forklift']],
             'after': ['Equipment availability should be confirmed according to the project requirement and rental period.']},
            {'eyebrow': 'المعدات المتوفرة', 'title': 'أسطول المعدات الثقيلة لدينا',
             'fleet': [['Backhoe Loaders', 'JCB 4CX Super Backhoe Loader · JCB Backhoe Loader', 'rental-backhoe'],
                       ['Telescopic Handlers', 'JCB 540-170 Telescopic Handler', 'rental-telehandler'],
                       ['Scissor Lifts', '10–14 Meter Scissor Lifts', 'rental-scissor'],
                       ['Forklifts', '3–16 Ton Forklifts · TCM 10 Ton Diesel Forklift · ZOOMLION Forklifts', 'rental-forklift']],
             'after': ['يجب تأكيد توفر المعدات وفقًا لمتطلبات المشروع ومدة التأجير.']},
            type='fleet', tone='soft'),
        pp('Construction & Excavation Equipment', 'Equipment for Site & Construction Operations',
           ['Our heavy equipment rental solutions support:'],
           'معدات البناء والحفر', 'معدات لعمليات المواقع والبناء', ['تدعم حلول تأجير المعدات الثقيلة لدينا:'],
           image='rental-construction', flip=True,
           en_tags='Construction | Excavation | Site Development', ar_tags='البناء | الحفر | تطوير المواقع',
           en_after=['Backhoe loaders and other heavy equipment can support material handling, excavation, earthmoving, and general construction activities according to project requirements.'],
           ar_after=['يمكن لمعدات Backhoe Loaders وغيرها من المعدات الثقيلة دعم مناولة المواد، والحفر، وتحريك التربة، وأنشطة البناء العامة وفقًا لمتطلبات المشروع.']),
        sec({'eyebrow': 'Road Building, Mining & Industrial Applications', 'title': 'Supporting Demanding Site Operations',
             'body': ['Our rental equipment can be used across a range of applications, including:'],
             'cards': [['Road Building & Paving', 'Equipment support for road construction, site preparation, and paving-related operations.'],
                       ['Mining & Quarrying', 'Heavy equipment for material handling and site activities within mining and quarrying environments.'],
                       ['Industrial Site Development', 'Equipment support for industrial construction, site preparation, and infrastructure development.'],
                       ['Waste Management', 'Heavy equipment solutions for material handling and waste management operations.']]},
            {'eyebrow': 'إنشاء الطرق والتعدين والتطبيقات الصناعية', 'title': 'دعم عمليات المواقع التي تتطلب معدات ثقيلة',
             'body': ['يمكن استخدام معدات التأجير لدينا في مجموعة واسعة من التطبيقات، بما في ذلك:'],
             'cards': [['إنشاء الطرق والرصف', 'دعم بالمعدات اللازمة لأعمال إنشاء الطرق، وتجهيز المواقع، وأعمال الرصف.'],
                       ['التعدين واستغلال المحاجر', 'معدات ثقيلة لمناولة المواد وتنفيذ أنشطة المواقع في بيئات التعدين واستغلال المحاجر.'],
                       ['تطوير المواقع الصناعية', 'دعم بالمعدات اللازمة لأعمال البناء الصناعي، وتجهيز المواقع، وتطوير البنية التحتية.'],
                       ['إدارة النفايات', 'حلول بالمعدات الثقيلة لمناولة المواد وعمليات إدارة النفايات.']]},
            type='cards'),
        sec({'eyebrow': 'Why Gulf Industrial Solutions', 'title': 'Practical Rental Solutions for Your Projects',
             'cards': [['Cost-Effective Equipment Access', 'Rent equipment according to project requirements without the upfront investment associated with ownership.'],
                       ['Flexible Rental Solutions', 'Access equipment based on your project and operational requirements.'],
                       ['Modern Equipment', 'Our rental fleet includes heavy machinery and equipment designed to support demanding project environments.'],
                       ['Maintenance Support', 'Equipment maintenance and servicing are handled as part of the rental service, allowing project teams to focus on their operations.']]},
            {'eyebrow': 'لماذا الخليج للحلول الصناعية', 'title': 'حلول تأجير عملية لمشاريعكم',
             'cards': [['الوصول إلى المعدات بتكلفة فعّالة', 'استأجروا المعدات وفقًا لمتطلبات المشروع دون الحاجة إلى الاستثمار المسبق المرتبط بامتلاك المعدات.'],
                       ['حلول تأجير مرنة', 'إتاحة المعدات وفقًا لمتطلبات مشروعكم واحتياجاتكم التشغيلية.'],
                       ['معدات حديثة', 'يشمل أسطول التأجير لدينا آليات ومعدات ثقيلة مصممة لدعم بيئات المشاريع التي تتطلب معدات موثوقة.'],
                       ['دعم الصيانة', 'تُجرى أعمال صيانة المعدات وخدمتها كجزء من خدمة التأجير، مما يتيح لفرق المشاريع التركيز على عملياتها.']]},
            type='cards', tone='soft'),
        sec({'eyebrow': 'From Equipment Rental to Project Support', 'title': 'Equipment for the Work You Need to Get Done',
             'body': ['Whether your requirement involves construction, excavation, road building, mining, industrial site development, or waste management, Gulf Industrial Solutions can provide suitable heavy equipment rental options based on your project requirements.'],
             'tags': pipes('Equipment | Availability | Rental | Support')},
            {'eyebrow': 'من تأجير المعدات إلى دعم المشاريع', 'title': 'المعدات اللازمة لإنجاز أعمالكم',
             'body': ['سواء كان مشروعكم يتعلق بالبناء، أو الحفر، أو إنشاء الطرق، أو التعدين، أو تطوير المواقع الصناعية، أو إدارة النفايات، يمكن للخليج للحلول الصناعية توفير خيارات مناسبة من المعدات الثقيلة للتأجير وفقًا لمتطلبات مشروعكم.'],
             'tags': pipes('المعدات | التوفر | التأجير | الدعم')},
            type='text', tone='dark'),
        CTA,
    ]}

# ---------------------------------------------------------------- About
PAGES['about'] = {
    'slug': 'about-us', 'hero_image': 'about-hero',
    'en': {'nav': 'About Us', 'eyebrow': 'Who We Are', 'title': 'Your Partner in Industrial Progress', 'line': 'A World of Possibilities'},
    'ar': {'nav': 'من نحن', 'eyebrow': 'من نحن', 'title': 'شريككم في التقدم الصناعي', 'line': 'عالم من الإمكانات'},
    'sections': [
        pp('Who We Are', 'Reliable technical expertise. Practical solutions.',
           ['Gulf Industrial Solutions is a growing industrial solutions provider committed to supporting manufacturing and production industries with reliable technical expertise and practical solutions.',
            'Our capabilities span engineering services, pulp & paper, corrugated packaging, water & wastewater solutions, and industrial equipment support.',
            'Through strategic partnerships, technical knowledge, and industry-focused solutions, we help our clients improve operational performance, production efficiency, and long-term reliability.',
            'Our mission is simple: to deliver the right solution for every industrial challenge from initial planning to successful execution and beyond.'],
           'من نحن', 'خبرة فنية موثوقة. حلول عملية.',
           ['الخليج للحلول الصناعية هي شركة متنامية في مجال الحلول الصناعية، تلتزم بدعم قطاعات التصنيع والإنتاج من خلال خبرات فنية موثوقة وحلول عملية.',
            'تشمل قدراتنا خدمات الهندسة، واللب والورق، والتغليف المموج، وحلول المياه ومياه الصرف الصحي، ودعم المعدات الصناعية.',
            'ومن خلال الشراكات الاستراتيجية، والمعرفة الفنية، والحلول المتخصصة التي تركز على احتياجات القطاعات الصناعية، نساعد عملاءنا على تحسين الأداء التشغيلي، وكفاءة الإنتاج، والموثوقية على المدى الطويل.',
            'مهمتنا بسيطة: تقديم الحل المناسب لكل تحدٍ صناعي، بدءًا من التخطيط الأولي وحتى التنفيذ الناجح وما بعده.'],
           image='about-team'),
        sec({'eyebrow': 'CEO Message', 'title': 'Empowering Industry Through Technical Solutions',
             'quote': 'To serve industries is one of the greatest passions of my life.',
             'body': ['My goal is to empower industry leaders through unique solutions that address their requirements today and support their opportunities for tomorrow.',
                      'I believe industrial services require a customised approach because every industrial requirement is different. For this reason, I focus on developing solutions according to the specific needs of each customer.',
                      'I also believe that industrial services should be approached as a technical profession rather than simply a commercial business activity. Our team therefore brings together professionals from diverse engineering, process and operations backgrounds.',
                      'With an engineering degree and more than 20 years of industrial experience covering production, research and development, and industrial development, I remain focused on delivering solutions with technical understanding and practical value.',
                      'Throughout my career, I have focused on serving clients with responsibility and respect while maintaining the quality of products and services. I believe in building long-term relationships based on commitment, care, and business ethics.',
                      'I welcome the opportunity to discuss your industrial requirements and explore the right techno-commercial solutions for your needs.'],
             'note': 'Chief Executive Officer, Gulf Industrial Solutions'},
            {'eyebrow': 'رسالة الرئيس التنفيذي', 'title': 'تمكين الصناعة من خلال حلول تقنية',
             'quote': 'خدمة القطاع الصناعي هي من أعظم شغفي في الحياة.',
             'body': ['هدفي هو تمكين قادة الصناعة من خلال حلول فريدة تلبي متطلباتهم اليوم وتدعم فرصهم في المستقبل.',
                      'أؤمن بأن الخدمات الصناعية تتطلب نهجًا مخصصًا، لأن كل متطلب صناعي يختلف عن الآخر. ولهذا السبب، أركّز على تطوير حلول وفقًا للاحتياجات المحددة لكل عميل.',
                      'كما أؤمن بأن الخدمات الصناعية ينبغي التعامل معها كمهنة تقنية، وليس مجرد نشاط تجاري. ولذلك، يضم فريقنا متخصصين من خلفيات متنوعة في مجالات الهندسة والعمليات والتشغيل.',
                      'بفضل حصولي على درجة جامعية في الهندسة وأكثر من 20 عامًا من الخبرة الصناعية التي تشمل الإنتاج، والبحث والتطوير، والتطوير الصناعي، أظل ملتزمًا بتقديم حلول تجمع بين الفهم التقني والقيمة العملية.',
                      'على مدار مسيرتي المهنية، ركّزت على خدمة العملاء بمسؤولية واحترام، مع الحفاظ على جودة المنتجات والخدمات. وأؤمن ببناء علاقات طويلة الأمد قائمة على الالتزام، والاهتمام، وأخلاقيات العمل.',
                      'يسعدني أن أناقش متطلباتكم الصناعية وأن نستكشف معًا الحلول التقنية والتجارية المناسبة لاحتياجاتكم.'],
             'note': 'الرئيس التنفيذي، الخليج للحلول الصناعية'},
            type='ceo', image='about-ceo', tone='soft'),
        sec({'eyebrow': 'Our Values', 'title': 'What guides our work',
             'cards': [['Commitment', 'We believe our commitment to our customers is an important part of the relationships we build and the services we provide.'],
                       ['Attitude', 'We focus on customer satisfaction and continued support throughout our relationship with clients.'],
                       ['Safety', 'We place importance on the safety of people and the environment across our activities, particularly within the paper and corrugated packaging industries.']]},
            {'eyebrow': 'قيمنا', 'title': 'ما يوجّه عملنا',
             'cards': [['الالتزام', 'نؤمن بأن التزامنا تجاه عملائنا يُعد جزءًا أساسيًا من العلاقات التي نبنيها والخدمات التي نقدمها.'],
                       ['التعامل مع العملاء', 'نركّز على رضا العملاء وتقديم الدعم المستمر طوال فترة علاقتنا معهم.'],
                       ['السلامة', 'نولي أهمية كبيرة لسلامة الأفراد والبيئة في جميع أنشطتنا، وبخاصة في قطاعي صناعة الورق وتغليف الكرتون المضلع.']]},
            type='cards'),
        sec({'eyebrow': 'Saudi Vision 2030', 'title': 'Supporting a Sustainable Industrial Future',
             'body': ['Through strategic partnerships and advanced technologies, Gulf Industrial Solutions is committed to advancing global best practices in engineering, manufacturing, and environmental solutions. Our goal is to support sustainable growth while promoting long-term environmental responsibility.',
                      'From water and wastewater treatment to industrial engineering and sustainable packaging, we provide efficient, innovative solutions that contribute to the objectives of Saudi Vision 2030 and help build a more sustainable industrial future.']},
            {'eyebrow': 'رؤية 2030', 'title': 'دعم مستقبل صناعي مستدام',
             'body': ['من خلال الشراكات الاستراتيجية والتقنيات المتقدمة، تلتزم الخليج للحلول الصناعية بتعزيز أفضل الممارسات العالمية في مجالات الهندسة والتصنيع والحلول البيئية. ونسعى إلى دعم النمو المستدام، مع تعزيز المسؤولية البيئية على المدى الطويل.',
                      'ومن معالجة المياه ومياه الصرف الصحي إلى الهندسة الصناعية وحلول التغليف المستدام، نقدم حلولًا مبتكرة وفعّالة تسهم في تحقيق مستهدفات رؤية السعودية 2030، وتدعم بناء مستقبل صناعي أكثر استدامة.']},
            type='text', tone='dark'),
        sec({'eyebrow': 'Our Group Companies', 'title': 'Part of a wider group',
             'body': ['Gulf Industrial Solutions is part of a wider group of companies serving different industrial and commercial requirements.'],
             'logos': 4},
            {'eyebrow': 'شركات مجموعتنا', 'title': 'جزء من مجموعة أوسع',
             'body': ['الخليج للحلول الصناعية هي جزء من مجموعة أوسع من الشركات التي تخدم مختلف المتطلبات الصناعية والتجارية.'],
             'logos': 4},
            type='logos', tone='soft'),
        CTA,
    ]}

# ---------------------------------------------------------------- Contact
OFFICES_EN = [
    ['Saudi Arabia', 'Gulf Industrial Company | شركة الخليج الصناعية', 'Office 21, 4th Floor, Bin Himad Center, King Fahad Rd, Jeddah 23443, Saudi Arabia', '+966 56 735 5540 | +966 59 606 0624'],
    ['Pakistan', 'Gulf Industrial Solutions', '75-Sunflower Society J-1, Johar Town, Lahore, Punjab, Pakistan', ''],
    ['United Kingdom', 'Gulf Industrial Solutions UK Ltd.', '589 Yardley Wood Road, Birmingham, B13 0TB, United Kingdom', ''],
    ['United Arab Emirates', 'Najm Al Thaqib Trading UAE', 'Office #102, Building #511, Muwaileh, Sharjah 22726, United Arab Emirates', ''],
    ['Oman', 'Shining Star International Oman', 'P.O. Box 221, Saham 319, Sultanate of Oman', ''],
]
AR_COUNTRIES = ['المملكة العربية السعودية', 'باكستان', 'المملكة المتحدة', 'الإمارات العربية المتحدة', 'عُمان']
PAGES['contact'] = {
    'slug': 'contact-us', 'hero_image': 'contact-hero',
    'en': {'nav': 'Contact Us', 'eyebrow': 'Contact Us', 'title': "Let's Discuss Your Industrial Requirements",
           'line': 'Get in Touch With Our Team',
           'text': 'Whether you need technical support, equipment, engineering services, water treatment solutions, packaging systems, or industrial project support, our team is ready to discuss your requirements.'},
    'ar': {'nav': 'تواصلوا معنا', 'eyebrow': 'تواصلوا معنا', 'title': 'لنناقش متطلباتكم الصناعية',
           'line': 'تواصلوا مع فريقنا',
           'text': 'سواء كنتم بحاجة إلى دعم فني، أو معدات، أو خدمات هندسية، أو حلول لمعالجة المياه، أو أنظمة تغليف، أو دعم لمشاريع صناعية، فإن فريقنا جاهز لمناقشة متطلباتكم.'},
    'sections': [
        sec({'eyebrow': 'Send Us Your Enquiry', 'title': 'Tell Us About Your Requirement',
             'body': ['Have a project in mind or need information about our industrial solutions? Fill in the form below and our team will get back to you.'],
             'ksa_title': 'KSA Team', 'ksa_text': 'For industrial projects, technical requirements, and business enquiries in Saudi Arabia.',
             'help_title': 'Need Immediate Assistance?', 'help_text': 'For enquiries related to Saudi Arabia, contact our KSA team directly.'},
            {'eyebrow': 'أرسلوا لنا استفساركم', 'title': 'شاركوا متطلباتكم معنا',
             'body': ['هل لديكم مشروع أو تحتاجون إلى معلومات حول حلولنا الصناعية؟ املأوا النموذج أدناه، وسيتواصل معكم فريقنا.'],
             'ksa_title': 'فريق المملكة العربية السعودية', 'ksa_text': 'للاستفسارات المتعلقة بالمشاريع الصناعية، والمتطلبات الفنية، والاستفسارات التجارية في المملكة العربية السعودية.',
             'help_title': 'هل تحتاجون إلى مساعدة فورية؟', 'help_text': 'للاستفسارات المتعلقة بالمملكة العربية السعودية، تواصلوا مع فريقنا مباشرة.'},
            type='form'),
        sec({'eyebrow': 'Our Offices', 'title': 'Where to find us', 'offices': OFFICES_EN},
            {'eyebrow': 'مكاتبنا', 'title': 'أين تجدوننا',
             'offices': [[AR_COUNTRIES[i]] + o[1:] for i, o in enumerate(OFFICES_EN)]},
            type='offices', tone='soft', image='contact-map'),
    ]}


def main():
    os.makedirs(OUT, exist_ok=True)
    index = {}
    for key, page in PAGES.items():
        for s in page['sections']:
            assert set(s) >= {'en', 'ar', 'type'}, s
        with open(os.path.join(OUT, key + '.json'), 'w', encoding='utf-8') as f:
            json.dump(page, f, ensure_ascii=False, indent=1)
        index[key] = {'slug': page['slug'], 'en': page['en']['nav'], 'ar': page['ar']['nav']}
    with open(os.path.join(OUT, 'index.json'), 'w', encoding='utf-8') as f:
        json.dump(index, f, ensure_ascii=False, indent=1)
    print('wrote', len(PAGES), 'pages')


if __name__ == '__main__':
    main()
