<?php defined('ABSPATH') || exit; ?>
<?php if ($section === 'hero'): ?>
<section class="gulf-hero" aria-labelledby="gulf-title"><?php gulf_image('home-hero', gulf_text('plant_alt'), 'gulf-hero-image', 'paper-plant.webp', true); ?>" alt="<?php echo esc_attr(gulf_text('plant_alt')); ?>" width="800" height="449" fetchpriority="high"><div class="gulf-wrap gulf-hero-content"><p class="gulf-eyebrow"><?php gulf_t('hero_eyebrow'); ?></p><h1 id="gulf-title"><?php gulf_t('brand'); ?></h1><p class="gulf-hero-line"><?php gulf_t('hero_line'); ?></p><p class="gulf-hero-description"><?php gulf_t('hero_description'); ?></p><div class="gulf-actions"><a class="gulf-button gulf-orange" href="#solutions"><?php gulf_t('explore'); ?> <span aria-hidden="true">↗</span></a><a class="gulf-text-link" href="<?php echo esc_url(gulf_link('contact', 'enquiry')); ?>"><?php gulf_t('discuss'); ?> <span aria-hidden="true">↗</span></a></div></div><div class="gulf-hero-caption"><span>01 /</span> <?php gulf_t('paper_title'); ?></div></section>
<div class="gulf-capability-strip"><div class="gulf-wrap"><span><?php gulf_t('strip_one'); ?></span><span><?php gulf_t('strip_two'); ?></span><span><?php gulf_t('strip_three'); ?></span></div></div>
<?php elseif ($section === 'intro'): ?>
<section class="gulf-section" id="about"><div class="gulf-wrap gulf-intro-grid"><div><p class="gulf-eyebrow"><?php gulf_t('nav_about'); ?></p><h2><?php gulf_t('intro_title'); ?></h2></div><div><p class="gulf-lead"><?php gulf_t('intro_lead'); ?></p><p><?php gulf_t('intro_body'); ?></p><a class="gulf-inline-link" href="<?php echo esc_url(gulf_link('about')); ?>"><?php gulf_t('read_more_about'); ?> <span aria-hidden="true">↗</span></a></div></div></section>
<?php elseif ($section === 'vision'): ?>
<section class="gulf-vision"><div class="gulf-wrap gulf-vision-grid"><div class="gulf-vision-number" aria-hidden="true">2030<span><?php gulf_t('vision_small'); ?></span></div><div><p class="gulf-eyebrow"><?php gulf_t('vision_eyebrow'); ?></p><h2><?php gulf_t('vision_title'); ?></h2><p><?php gulf_t('vision_body'); ?></p><div class="gulf-vision-points"><span><?php gulf_t('vision_one'); ?></span><span><?php gulf_t('vision_two'); ?></span><span><?php gulf_t('vision_three'); ?></span></div></div></div></section>
<?php elseif ($section === 'solutions'): ?>
<section class="gulf-section gulf-solutions" id="solutions"><div class="gulf-wrap"><div class="gulf-section-heading"><div><p class="gulf-eyebrow"><?php gulf_t('solutions_eyebrow'); ?></p><h2><?php gulf_t('solutions_title'); ?></h2></div><p><?php gulf_t('solutions_intro'); ?></p></div><div class="gulf-solutions-grid">
<?php $gulf_map = array('engineering' => 'engineering', 'paper' => 'pulp-paper', 'packaging' => 'corrugated', 'water' => 'water', 'rental' => 'rental', 'support' => 'contact'); foreach ($gulf_map as $item => $target): $i = array_search($item, array_keys($gulf_map), true); ?>
<article class="gulf-solution"><div class="gulf-solution-top"><span><?php echo esc_html(sprintf('%02d', $i + 1)); ?></span></div><h3><?php gulf_t($item . '_title'); ?></h3><p><?php gulf_t($item . '_body'); ?></p><details><summary><?php gulf_t('capabilities'); ?></summary><p><?php gulf_t($item . '_detail'); ?></p></details><a class="gulf-inline-link gulf-solution-link" href="<?php echo esc_url(gulf_link($target)); ?>"><?php gulf_t($target === 'contact' ? 'discuss' : 'view_solution'); ?> <span aria-hidden="true">↗</span></a></article>
<?php endforeach; ?></div></div></section>
<?php elseif ($section === 'industries'): ?>
<section class="gulf-section gulf-industries" id="industries"><div class="gulf-wrap gulf-industry-grid"><div class="gulf-industry-photo"><img src="<?php echo esc_url(gulf_asset('equipment.jpg')); ?>" alt="<?php echo esc_attr(gulf_text('equipment_alt')); ?>" width="1000" height="1000" loading="lazy"></div><div><p class="gulf-eyebrow"><?php gulf_t('nav_industries'); ?></p><h2><?php gulf_t('industries_title'); ?></h2><p><?php gulf_t('industries_body'); ?></p><ul class="gulf-sector-list"><?php foreach (array('sector_one','sector_two','sector_three','sector_four','sector_five') as $i => $key): ?><li><span><?php gulf_t($key); ?></span><span aria-hidden="true">↗</span></li><?php endforeach; ?></ul></div></div></section>
<?php elseif ($section === 'process'): ?>
<section class="gulf-section" id="process"><div class="gulf-wrap"><p class="gulf-eyebrow"><?php gulf_t('our_approach'); ?></p><h2><?php gulf_t('process_title'); ?></h2><div class="gulf-process-grid"><?php foreach (array('understand','plan','deliver') as $i => $key): ?><article><span class="gulf-step">0<?php echo esc_html($i + 1); ?></span><h3><?php gulf_t($key . '_title'); ?></h3><p><?php gulf_t($key . '_body'); ?></p></article><?php endforeach; ?></div></div></section>
<?php elseif ($section === 'why'): ?>
<section class="gulf-section gulf-tone-soft" id="why"><div class="gulf-wrap"><div class="gulf-section-heading"><div><p class="gulf-eyebrow"><?php gulf_t('why_eyebrow'); ?></p><h2><?php gulf_t('why_title'); ?></h2></div><p><?php gulf_t('why_body'); ?></p></div><div class="gulf-cards gulf-cards-2"><?php foreach (array('one','two','three','four') as $n => $k): ?><article class="gulf-card"><span class="gulf-card-num"><?php echo esc_html(sprintf('%02d', $n + 1)); ?></span><h3><?php gulf_t('why_' . $k . '_title'); ?></h3><p><?php gulf_t('why_' . $k . '_body'); ?></p></article><?php endforeach; ?></div></div></section>
<?php elseif ($section === 'partners'): ?>
<section class="gulf-section" id="partners"><div class="gulf-wrap"><div class="gulf-section-heading"><div><p class="gulf-eyebrow"><?php gulf_t('partners_eyebrow'); ?></p><h2><?php gulf_t('partners_title'); ?></h2></div><p><?php gulf_t('partners_body'); ?></p></div><div class="gulf-logos"><?php for ($l = 1; $l <= 6; $l++) { gulf_image('partner-logo-' . $l, ''); } ?></div></div></section>
<?php elseif ($section === 'contact'): ?>
<section class="gulf-contact" id="contact"><div class="gulf-wrap gulf-contact-grid"><div><p class="gulf-eyebrow"><?php gulf_t('contact_eyebrow'); ?></p><h2><?php gulf_t('contact_title'); ?></h2><p><?php gulf_t('contact_body'); ?></p></div><div class="gulf-contact-actions"><a class="gulf-button gulf-orange" href="<?php echo esc_url(gulf_link('contact', 'enquiry')); ?>"><?php gulf_t('submit_enquiry'); ?> <span aria-hidden="true">↗</span></a><a class="gulf-button gulf-ghost" href="<?php echo esc_url(GULF_WHATSAPP); ?>" rel="noopener"><?php gulf_t('contact_team'); ?> <span aria-hidden="true">↗</span></a><a class="gulf-contact-phone" href="tel:+966567355540" dir="ltr">+966 56 735 5540</a><span><?php gulf_t('contact_location'); ?></span></div></div></section>
<?php endif; ?>
