<?php
// ===== QURBA: 99 Names of Allah for the admin (same list as resources/js/lib/asmaulHusna.ts) =====
namespace App\Support\Quran;

class NamesOfAllah
{
    /** @return array<int, array{n:int, ar:string, tr:string, en:string}> */
    public static function all(): array
    {
        return [
            ['n' => 1, 'ar' => "الرَّحْمَٰنُ", 'tr' => "Ar-Rahman", 'en' => "The Most Gracious"],
            ['n' => 2, 'ar' => "الرَّحِيمُ", 'tr' => "Ar-Rahim", 'en' => "The Most Merciful"],
            ['n' => 3, 'ar' => "الْمَلِكُ", 'tr' => "Al-Malik", 'en' => "The King"],
            ['n' => 4, 'ar' => "الْقُدُّوسُ", 'tr' => "Al-Quddus", 'en' => "The Most Holy"],
            ['n' => 5, 'ar' => "السَّلَامُ", 'tr' => "As-Salam", 'en' => "The Source of Peace"],
            ['n' => 6, 'ar' => "الْمُؤْمِنُ", 'tr' => "Al-Mu'min", 'en' => "The Giver of Security"],
            ['n' => 7, 'ar' => "الْمُهَيْمِنُ", 'tr' => "Al-Muhaymin", 'en' => "The Guardian"],
            ['n' => 8, 'ar' => "الْعَزِيزُ", 'tr' => "Al-'Aziz", 'en' => "The Almighty"],
            ['n' => 9, 'ar' => "الْجَبَّارُ", 'tr' => "Al-Jabbar", 'en' => "The Compeller"],
            ['n' => 10, 'ar' => "الْمُتَكَبِّرُ", 'tr' => "Al-Mutakabbir", 'en' => "The Supreme in Greatness"],
            ['n' => 11, 'ar' => "الْخَالِقُ", 'tr' => "Al-Khaliq", 'en' => "The Creator"],
            ['n' => 12, 'ar' => "الْبَارِئُ", 'tr' => "Al-Bari'", 'en' => "The Maker"],
            ['n' => 13, 'ar' => "الْمُصَوِّرُ", 'tr' => "Al-Musawwir", 'en' => "The Fashioner of Forms"],
            ['n' => 14, 'ar' => "الْغَفَّارُ", 'tr' => "Al-Ghaffar", 'en' => "The Ever-Forgiving"],
            ['n' => 15, 'ar' => "الْقَهَّارُ", 'tr' => "Al-Qahhar", 'en' => "The Subduer"],
            ['n' => 16, 'ar' => "الْوَهَّابُ", 'tr' => "Al-Wahhab", 'en' => "The Bestower"],
            ['n' => 17, 'ar' => "الرَّزَّاقُ", 'tr' => "Ar-Razzaq", 'en' => "The Provider"],
            ['n' => 18, 'ar' => "الْفَتَّاحُ", 'tr' => "Al-Fattah", 'en' => "The Opener"],
            ['n' => 19, 'ar' => "الْعَلِيمُ", 'tr' => "Al-'Alim", 'en' => "The All-Knowing"],
            ['n' => 20, 'ar' => "الْقَابِضُ", 'tr' => "Al-Qabid", 'en' => "The Withholder"],
            ['n' => 21, 'ar' => "الْبَاسِطُ", 'tr' => "Al-Basit", 'en' => "The Extender"],
            ['n' => 22, 'ar' => "الْخَافِضُ", 'tr' => "Al-Khafid", 'en' => "The Abaser"],
            ['n' => 23, 'ar' => "الرَّافِعُ", 'tr' => "Ar-Rafi'", 'en' => "The Exalter"],
            ['n' => 24, 'ar' => "الْمُعِزُّ", 'tr' => "Al-Mu'izz", 'en' => "The Giver of Honour"],
            ['n' => 25, 'ar' => "الْمُذِلُّ", 'tr' => "Al-Mudhill", 'en' => "The Giver of Dishonour"],
            ['n' => 26, 'ar' => "السَّمِيعُ", 'tr' => "As-Sami'", 'en' => "The All-Hearing"],
            ['n' => 27, 'ar' => "الْبَصِيرُ", 'tr' => "Al-Basir", 'en' => "The All-Seeing"],
            ['n' => 28, 'ar' => "الْحَكَمُ", 'tr' => "Al-Hakam", 'en' => "The Judge"],
            ['n' => 29, 'ar' => "الْعَدْلُ", 'tr' => "Al-'Adl", 'en' => "The Just"],
            ['n' => 30, 'ar' => "اللَّطِيفُ", 'tr' => "Al-Latif", 'en' => "The Subtle, the Kind"],
            ['n' => 31, 'ar' => "الْخَبِيرُ", 'tr' => "Al-Khabir", 'en' => "The All-Aware"],
            ['n' => 32, 'ar' => "الْحَلِيمُ", 'tr' => "Al-Halim", 'en' => "The Forbearing"],
            ['n' => 33, 'ar' => "الْعَظِيمُ", 'tr' => "Al-'Azim", 'en' => "The Magnificent"],
            ['n' => 34, 'ar' => "الْغَفُورُ", 'tr' => "Al-Ghafur", 'en' => "The All-Forgiving"],
            ['n' => 35, 'ar' => "الشَّكُورُ", 'tr' => "Ash-Shakur", 'en' => "The Most Appreciative"],
            ['n' => 36, 'ar' => "الْعَلِيُّ", 'tr' => "Al-'Aliyy", 'en' => "The Most High"],
            ['n' => 37, 'ar' => "الْكَبِيرُ", 'tr' => "Al-Kabir", 'en' => "The Most Great"],
            ['n' => 38, 'ar' => "الْحَفِيظُ", 'tr' => "Al-Hafiz", 'en' => "The Preserver"],
            ['n' => 39, 'ar' => "الْمُقِيتُ", 'tr' => "Al-Muqit", 'en' => "The Nourisher"],
            ['n' => 40, 'ar' => "الْحَسِيبُ", 'tr' => "Al-Hasib", 'en' => "The Reckoner"],
            ['n' => 41, 'ar' => "الْجَلِيلُ", 'tr' => "Al-Jalil", 'en' => "The Majestic"],
            ['n' => 42, 'ar' => "الْكَرِيمُ", 'tr' => "Al-Karim", 'en' => "The Most Generous"],
            ['n' => 43, 'ar' => "الرَّقِيبُ", 'tr' => "Ar-Raqib", 'en' => "The Watchful"],
            ['n' => 44, 'ar' => "الْمُجِيبُ", 'tr' => "Al-Mujib", 'en' => "The Responsive"],
            ['n' => 45, 'ar' => "الْوَاسِعُ", 'tr' => "Al-Wasi'", 'en' => "The All-Encompassing"],
            ['n' => 46, 'ar' => "الْحَكِيمُ", 'tr' => "Al-Hakim", 'en' => "The All-Wise"],
            ['n' => 47, 'ar' => "الْوَدُودُ", 'tr' => "Al-Wadud", 'en' => "The Most Loving"],
            ['n' => 48, 'ar' => "الْمَجِيدُ", 'tr' => "Al-Majid", 'en' => "The Most Glorious"],
            ['n' => 49, 'ar' => "الْبَاعِثُ", 'tr' => "Al-Ba'ith", 'en' => "The Resurrector"],
            ['n' => 50, 'ar' => "الشَّهِيدُ", 'tr' => "Ash-Shahid", 'en' => "The Witness"],
            ['n' => 51, 'ar' => "الْحَقُّ", 'tr' => "Al-Haqq", 'en' => "The Truth"],
            ['n' => 52, 'ar' => "الْوَكِيلُ", 'tr' => "Al-Wakil", 'en' => "The Trustee"],
            ['n' => 53, 'ar' => "الْقَوِيُّ", 'tr' => "Al-Qawiyy", 'en' => "The Most Strong"],
            ['n' => 54, 'ar' => "الْمَتِينُ", 'tr' => "Al-Matin", 'en' => "The Firm"],
            ['n' => 55, 'ar' => "الْوَلِيُّ", 'tr' => "Al-Waliyy", 'en' => "The Protecting Friend"],
            ['n' => 56, 'ar' => "الْحَمِيدُ", 'tr' => "Al-Hamid", 'en' => "The Praiseworthy"],
            ['n' => 57, 'ar' => "الْمُحْصِي", 'tr' => "Al-Muhsi", 'en' => "The All-Enumerating"],
            ['n' => 58, 'ar' => "الْمُبْدِئُ", 'tr' => "Al-Mubdi'", 'en' => "The Originator"],
            ['n' => 59, 'ar' => "الْمُعِيدُ", 'tr' => "Al-Mu'id", 'en' => "The Restorer"],
            ['n' => 60, 'ar' => "الْمُحْيِي", 'tr' => "Al-Muhyi", 'en' => "The Giver of Life"],
            ['n' => 61, 'ar' => "الْمُمِيتُ", 'tr' => "Al-Mumit", 'en' => "The Taker of Life"],
            ['n' => 62, 'ar' => "الْحَيُّ", 'tr' => "Al-Hayy", 'en' => "The Ever-Living"],
            ['n' => 63, 'ar' => "الْقَيُّومُ", 'tr' => "Al-Qayyum", 'en' => "The Self-Subsisting"],
            ['n' => 64, 'ar' => "الْوَاجِدُ", 'tr' => "Al-Wajid", 'en' => "The Finder"],
            ['n' => 65, 'ar' => "الْمَاجِدُ", 'tr' => "Al-Majid", 'en' => "The Noble"],
            ['n' => 66, 'ar' => "الْوَاحِدُ", 'tr' => "Al-Wahid", 'en' => "The One"],
            ['n' => 67, 'ar' => "الْأَحَدُ", 'tr' => "Al-Ahad", 'en' => "The Unique"],
            ['n' => 68, 'ar' => "الصَّمَدُ", 'tr' => "As-Samad", 'en' => "The Eternal Refuge"],
            ['n' => 69, 'ar' => "الْقَادِرُ", 'tr' => "Al-Qadir", 'en' => "The All-Capable"],
            ['n' => 70, 'ar' => "الْمُقْتَدِرُ", 'tr' => "Al-Muqtadir", 'en' => "The All-Powerful"],
            ['n' => 71, 'ar' => "الْمُقَدِّمُ", 'tr' => "Al-Muqaddim", 'en' => "The Expediter"],
            ['n' => 72, 'ar' => "الْمُؤَخِّرُ", 'tr' => "Al-Mu'akhkhir", 'en' => "The Delayer"],
            ['n' => 73, 'ar' => "الْأَوَّلُ", 'tr' => "Al-Awwal", 'en' => "The First"],
            ['n' => 74, 'ar' => "الْآخِرُ", 'tr' => "Al-Akhir", 'en' => "The Last"],
            ['n' => 75, 'ar' => "الظَّاهِرُ", 'tr' => "Az-Zahir", 'en' => "The Manifest"],
            ['n' => 76, 'ar' => "الْبَاطِنُ", 'tr' => "Al-Batin", 'en' => "The Hidden"],
            ['n' => 77, 'ar' => "الْوَالِي", 'tr' => "Al-Wali", 'en' => "The Governor"],
            ['n' => 78, 'ar' => "الْمُتَعَالِي", 'tr' => "Al-Muta'ali", 'en' => "The Most Exalted"],
            ['n' => 79, 'ar' => "الْبَرُّ", 'tr' => "Al-Barr", 'en' => "The Source of Goodness"],
            ['n' => 80, 'ar' => "التَّوَّابُ", 'tr' => "At-Tawwab", 'en' => "The Accepter of Repentance"],
            ['n' => 81, 'ar' => "الْمُنْتَقِمُ", 'tr' => "Al-Muntaqim", 'en' => "The Avenger"],
            ['n' => 82, 'ar' => "الْعَفُوُّ", 'tr' => "Al-'Afuww", 'en' => "The Pardoner"],
            ['n' => 83, 'ar' => "الرَّءُوفُ", 'tr' => "Ar-Ra'uf", 'en' => "The Most Kind"],
            ['n' => 84, 'ar' => "مَالِكُ الْمُلْكِ", 'tr' => "Malik al-Mulk", 'en' => "Owner of All Sovereignty"],
            ['n' => 85, 'ar' => "ذُو الْجَلَالِ وَالْإِكْرَامِ", 'tr' => "Dhul-Jalali wal-Ikram", 'en' => "Lord of Majesty and Honour"],
            ['n' => 86, 'ar' => "الْمُقْسِطُ", 'tr' => "Al-Muqsit", 'en' => "The Equitable"],
            ['n' => 87, 'ar' => "الْجَامِعُ", 'tr' => "Al-Jami'", 'en' => "The Gatherer"],
            ['n' => 88, 'ar' => "الْغَنِيُّ", 'tr' => "Al-Ghaniyy", 'en' => "The Self-Sufficient"],
            ['n' => 89, 'ar' => "الْمُغْنِي", 'tr' => "Al-Mughni", 'en' => "The Enricher"],
            ['n' => 90, 'ar' => "الْمَانِعُ", 'tr' => "Al-Mani'", 'en' => "The Preventer"],
            ['n' => 91, 'ar' => "الضَّارُّ", 'tr' => "Ad-Darr", 'en' => "The Bringer of Harm"],
            ['n' => 92, 'ar' => "النَّافِعُ", 'tr' => "An-Nafi'", 'en' => "The Bringer of Benefit"],
            ['n' => 93, 'ar' => "النُّورُ", 'tr' => "An-Nur", 'en' => "The Light"],
            ['n' => 94, 'ar' => "الْهَادِي", 'tr' => "Al-Hadi", 'en' => "The Guide"],
            ['n' => 95, 'ar' => "الْبَدِيعُ", 'tr' => "Al-Badi'", 'en' => "The Incomparable Originator"],
            ['n' => 96, 'ar' => "الْبَاقِي", 'tr' => "Al-Baqi", 'en' => "The Everlasting"],
            ['n' => 97, 'ar' => "الْوَارِثُ", 'tr' => "Al-Warith", 'en' => "The Inheritor"],
            ['n' => 98, 'ar' => "الرَّشِيدُ", 'tr' => "Ar-Rashid", 'en' => "The Guide to the Right Path"],
            ['n' => 99, 'ar' => "الصَّبُورُ", 'tr' => "As-Sabur", 'en' => "The Most Patient"],
        ];
    }
}
